import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, test } from "vitest";
import { classifyArtifactFromFilesystem } from "./artifact-classifier.js";

async function createSystemdReleaseFixture(input: {
  worldPackage?: string;
  worldVersion?: string;
  nested?: boolean;
}): Promise<string> {
  const releaseDir = await mkdtemp(path.join(os.tmpdir(), "eveland-release-"));
  const agentRoot = input.nested ? path.join(releaseDir, "agent") : releaseDir;
  await mkdir(agentRoot, { recursive: true });
  if (input.worldPackage) {
    await writeFile(
      path.join(agentRoot, "agent.ts"),
      `// Generated by Eveland in the prepared Release; imported source is unchanged.
export default {
  model: "anthropic/claude-sonnet-5",
  experimental: {
    workflow: {
      world: ${JSON.stringify(input.worldPackage)},
    },
  },
};
`,
    );
    const manifestDir = path.join(releaseDir, "node_modules", input.worldPackage);
    await mkdir(manifestDir, { recursive: true });
    await writeFile(
      path.join(manifestDir, "package.json"),
      JSON.stringify({ name: input.worldPackage, version: input.worldVersion ?? "0.9.0" }),
    );
  }
  return releaseDir;
}

describe("classifyArtifactFromFilesystem", () => {
  test("reads the injected world and its installed version from a systemd artifact", async () => {
    const releaseDir = await createSystemdReleaseFixture({
      worldPackage: "@evelandhq/workflow-world",
      worldVersion: "0.9.0",
      nested: true,
    });
    await expect(
      classifyArtifactFromFilesystem({ releaseRef: releaseDir, runtimeKind: "systemd" }),
    ).resolves.toEqual({
      worldKind: "shared",
      worldPackage: "@evelandhq/workflow-world",
      worldVersion: "0.9.0",
      storageSpec: 6,
      dispatchProtocol: 1,
      enqueueCapability: "per_run_queue_v1",
    });
  });

  test("an early shared artifact attests unscoped — capabilities are version facts", async () => {
    const releaseDir = await createSystemdReleaseFixture({
      worldPackage: "@evelandhq/workflow-world",
      worldVersion: "0.4.0",
    });
    await expect(
      classifyArtifactFromFilesystem({ releaseRef: releaseDir, runtimeKind: "systemd" }),
    ).resolves.toMatchObject({
      worldKind: "shared",
      worldVersion: "0.4.0",
      enqueueCapability: "unscoped",
      dispatchProtocol: null,
    });
  });

  test("a legacy artifact classifies as legacy_project", async () => {
    const releaseDir = await createSystemdReleaseFixture({
      worldPackage: "@workflow/world-postgres",
      worldVersion: "5.0.0-beta.34",
    });
    await expect(
      classifyArtifactFromFilesystem({ releaseRef: releaseDir, runtimeKind: "systemd" }),
    ).resolves.toMatchObject({
      worldKind: "legacy_project",
      enqueueCapability: "unscoped",
    });
  });

  test("stays unknown for docker artifacts and unreadable directories", async () => {
    const releaseDir = await createSystemdReleaseFixture({});
    await expect(
      classifyArtifactFromFilesystem({ releaseRef: releaseDir, runtimeKind: "systemd" }),
    ).resolves.toBeNull();
    await expect(
      classifyArtifactFromFilesystem({ releaseRef: "eveland/proj:rel", runtimeKind: "docker" }),
    ).resolves.toBeNull();
  });
});
