import type { EveProjectLayout, EveProjectSummary } from "./source.js";

/**
 * Projection of eve's own post-build artifact `.eve/discovery/agent-discovery-manifest.json`
 * onto the platform summary shape. Once a Release has been built, this manifest -- not
 * Eveland's pre-install static file scan -- is the authority on what the agent contains:
 * it is produced by `eve info` from the same installed tree `eve build` compiled, so it cannot
 * drift from eve's layout rules the way re-derived heuristics can.
 *
 * Fail closed to null: this projection replaces the static entity lists wholesale, so
 * a manifest with an unknown schema version or missing entity arrays must not become
 * "authoritative emptiness". The caller keeps the static summary instead. The
 * agent-observer compatibility matrix runs this projection on manifests generated live
 * by every pinned eve binary, so a schema bump fails the matrix, not production.
 */
export type DiscoverySummaryProjection = {
  summarySource: "build-manifest";
  manifestVersion: number;
  agentId: string | null;
  layout: EveProjectLayout;
  diagnostics: { errors: number; warnings: number } | null;
  hooks: string[];
  channels: string[];
  subagentIds: string[];
  // `agents` (the root agent config module) and `capabilities.eveChat` stay
  // owned by the static scan: the manifest neither lists the root config
  // module nor exposes what an authored channel module exports.
} & Omit<EveProjectSummary, "agents">;

const MANIFEST_KIND = "eve-agent-discovery-manifest";

/**
 * Verified against the manifests generated by every Eve compatibility line:
 * 0.47.x and 0.49.x both emit v15. v14 (0.45.0 only) left with the 0.45 line
 * on 2026-09-02, v13 with the 0.44 line before it.
 */
export const SUPPORTED_DISCOVERY_MANIFEST_VERSIONS: readonly number[] = [15];

const ENTITY_ARRAY_KEYS = [
  "instructions",
  "tools",
  "skills",
  "subagents",
  "connections",
  "schedules",
  "hooks",
  "channels",
] as const;

export function projectDiscoveryManifest(manifest: unknown): DiscoverySummaryProjection | null {
  if (!isRecord(manifest) || manifest.kind !== MANIFEST_KIND) return null;
  const version = manifest.version;
  if (typeof version !== "number" || !SUPPORTED_DISCOVERY_MANIFEST_VERSIONS.includes(version)) {
    return null;
  }
  // Every entity list must be present as an actual array of well-formed
  // entries, and sandbox must be the documented null-or-entry shape. A
  // manifest missing them -- or carrying elements without a logicalPath -- is
  // not "empty", it is unrecognized: silently dropping a corrupt element would
  // still overwrite the static entity lists with authoritative-looking data.
  for (const key of ENTITY_ARRAY_KEYS) {
    const value = manifest[key];
    if (!Array.isArray(value) || !value.every(isEntry)) return null;
  }
  if (manifest.sandbox !== null && !isEntry(manifest.sandbox)) return null;
  if (
    version >= 13 &&
    (!Array.isArray(manifest.extensions) ||
      !manifest.extensions.every(isEntry) ||
      !Array.isArray(manifest.resolvedExtensions) ||
      !manifest.resolvedExtensions.every(isResolvedExtensionMount))
  ) {
    return null;
  }

  const agentRoot = typeof manifest.agentRoot === "string" ? manifest.agentRoot : null;
  const appRoot = typeof manifest.appRoot === "string" ? manifest.appRoot : null;
  if (!agentRoot || !appRoot) return null;
  const layout: EveProjectLayout = agentRoot === appRoot ? "flat" : "nested";
  // Summary paths stay app-root-relative like the static scan's, so UI consumers
  // need no awareness of which producer wrote the summary.
  const root = layout === "nested" ? "agent/" : "";
  const prefix = (paths: string[]) => paths.map((entry) => `${root}${entry}`);

  const subagents = readEntries(manifest.subagents);
  const extensionContributions = readExtensionContributions(manifest.resolvedExtensions, root);

  return {
    summarySource: "build-manifest",
    manifestVersion: version,
    agentId: typeof manifest.agentId === "string" ? manifest.agentId : null,
    layout,
    diagnostics: readDiagnostics(manifest.diagnosticsSummary),
    instructions: prefix(logicalPaths(manifest.instructions)),
    tools: prefix(logicalPaths(manifest.tools)),
    skills: prefix(logicalPaths(manifest.skills)),
    subagents: [
      ...prefix(subagents.map((entry) => entry.logicalPath)),
      ...extensionContributions.subagents.map((entry) => entry.path),
    ],
    connections: prefix(logicalPaths(manifest.connections)),
    schedules: [...prefix(logicalPaths(manifest.schedules)), ...extensionContributions.schedules],
    sandbox: prefix(logicalPaths(manifest.sandbox === null ? [] : [manifest.sandbox])),
    hooks: prefix(logicalPaths(manifest.hooks)),
    channels: prefix(logicalPaths(manifest.channels)),
    subagentIds: [
      ...subagents
        .map((entry) => entry.subagentId)
        .filter((value): value is string => typeof value === "string"),
      ...extensionContributions.subagents.map((entry) => entry.id),
    ],
  };
}

type ExtensionManifestProjection = {
  agentRoot: string;
  schedules: Array<{ logicalPath: string }>;
  subagents: Array<{ logicalPath: string; subagentId?: unknown }>;
};

type ResolvedExtensionProjection = {
  namespace: string;
  manifest: ExtensionManifestProjection;
  overrides?: ExtensionManifestProjection;
};

function readExtensionContributions(
  value: unknown,
  root: string,
): { schedules: string[]; subagents: Array<{ id: string; path: string }> } {
  if (!Array.isArray(value)) return { schedules: [], subagents: [] };
  const schedules: string[] = [];
  const subagents: Array<{ id: string; path: string }> = [];
  const mounts = value
    .filter(isResolvedExtensionMount)
    .sort((left, right) => left.namespace.localeCompare(right.namespace));

  for (const mount of mounts) {
    const effectiveSchedules = mergeNamedEntries(
      mount.overrides?.schedules ?? [],
      mount.manifest.schedules,
      scheduleName,
    );
    schedules.push(
      ...effectiveSchedules.map(
        (entry) => `${root}extensions/${mount.namespace}/${entry.logicalPath}`,
      ),
    );

    const effectiveSubagents = mergeNamedEntries(
      mount.overrides?.subagents ?? [],
      mount.manifest.subagents,
      (entry) => (typeof entry.subagentId === "string" ? entry.subagentId : entry.logicalPath),
    );
    for (const entry of effectiveSubagents) {
      if (typeof entry.subagentId !== "string") continue;
      subagents.push({
        id: `${mount.namespace}__${entry.subagentId}`,
        path: `${root}extensions/${mount.namespace}/${entry.logicalPath}`,
      });
    }
  }
  return { schedules, subagents };
}

function mergeNamedEntries<T>(primary: T[], secondary: T[], name: (entry: T) => string): T[] {
  const names = new Set<string>();
  const merged: T[] = [];
  for (const entry of [...primary, ...secondary]) {
    const key = name(entry);
    if (names.has(key)) continue;
    names.add(key);
    merged.push(entry);
  }
  return merged;
}

function scheduleName(entry: { logicalPath: string }): string {
  const relative = entry.logicalPath.replace(/^schedules\//, "");
  return relative.replace(/\.(?:md|[cm]?[jt]s)$/, "");
}

function isResolvedExtensionMount(value: unknown): value is ResolvedExtensionProjection {
  if (!isRecord(value) || typeof value.namespace !== "string" || !value.namespace) return false;
  if (!isExtensionManifest(value.manifest)) return false;
  return value.overrides === undefined || isExtensionManifest(value.overrides);
}

function isExtensionManifest(value: unknown): value is ExtensionManifestProjection {
  return (
    isRecord(value) &&
    typeof value.agentRoot === "string" &&
    Array.isArray(value.schedules) &&
    value.schedules.every(isSupportedExtensionScheduleEntry) &&
    Array.isArray(value.subagents) &&
    value.subagents.every(isEntry)
  );
}

function isSupportedExtensionScheduleEntry(value: unknown): value is { logicalPath: string } {
  if (!isEntry(value)) return false;
  const normalized = value.logicalPath.replaceAll("\\", "/");
  if (!normalized.startsWith("schedules/")) return false;
  const relative = normalized.slice("schedules/".length);
  if (
    !relative ||
    relative.split("/").some((segment) => !segment || segment === "." || segment === "..")
  ) {
    return false;
  }
  return /\.(?:md|[cm]?[jt]s)$/.test(relative);
}

function isEntry(value: unknown): value is { logicalPath: string } {
  return isRecord(value) && typeof value.logicalPath === "string";
}

function readEntries(value: unknown): Array<{ logicalPath: string; subagentId?: unknown }> {
  if (!Array.isArray(value)) return [];
  return value.filter(
    (entry): entry is { logicalPath: string; subagentId?: unknown } =>
      isRecord(entry) && typeof entry.logicalPath === "string",
  );
}

function logicalPaths(value: unknown): string[] {
  return readEntries(Array.isArray(value) ? value : [value]).map((entry) => entry.logicalPath);
}

function readDiagnostics(value: unknown): { errors: number; warnings: number } | null {
  if (!isRecord(value) || typeof value.errors !== "number" || typeof value.warnings !== "number")
    return null;
  return { errors: value.errors, warnings: value.warnings };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
