// End-to-end proof, in the real Lima VM, that an imported eve project gets a
// working bwrap sandbox it never declared, and that a redeploy preserves the
// durable session workspace. Two layers combine to prove this, and both are
// required for the script to report success:
//   - A deterministic check that imports the generated agent/sandbox/sandbox.js
//     directly, deliberately bypassing eve's own session/runtime APIs. This
//     proves the generated module resolves to the real bwrap backend and
//     honors EVELAND_SANDBOX_CACHE_DIR, but says nothing about whether eve's
//     compiled runtime ever actually loads that module.
//   - A required live HTTP turn (runLiveHttpTurn) driven through eve's
//     deployed .output runtime. This is the only proof that eve's compiled
//     runtime -- not just the generated module in isolation -- invokes the
//     injected bwrap backend for a real turn.
// Plain tsx script (no vitest) run against the real store + processNextJob
// pipeline with EVELAND_RUNTIME=systemd, exactly as systemd-smoke.ts does.
import assert from "node:assert/strict";
import { execa } from "execa";
import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import { setTimeout as delay } from "node:timers/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import type { DeploymentRecord } from "@eveland/core/contracts";
import { encryptSecretValue } from "@eveland/core/server/secrets";
import { materializeEveFixtureDirectory } from "@eveland/core/server/eve-fixture";
import { createPgliteTestStore } from "@eveland/db/test";
import { processNextJob } from "../jobs/process.js";
import { resolveRuntimeKind } from "../runtime/select.js";
import {
  resolveProjectSandboxCacheDir,
  resolveSandboxCacheRoot,
  resolveSystemdDeploymentUser,
} from "../runtime/systemd.js";

if (resolveRuntimeKind(process.env) !== "systemd") {
  throw new Error("Run with EVELAND_RUNTIME=systemd (this test exercises the systemd + bwrap sandbox injection path).");
}

// Matches jobs/process.ts's own dev fallback. Passed explicitly to every
// processNextJob call below so secret encryption/decryption never depends on
// an ambient APP_SECRET_KEY the VM shell may or may not have set.
const APP_SECRET_KEY = process.env.APP_SECRET_KEY ?? "eveland-dev-secret-key-000000000";
const DEPLOY_ACCESS_GROUP =
  process.env.EVELAND_APP_USER ?? "eveland-app";
const FIXTURE_SOURCE_PATH = fileURLToPath(new URL("./fixtures/agent-sandbox-e2e", import.meta.url));

const TEMPLATE_KEY = "e2e-template";
const SESSION_KEY = "e2e-durable-session";
const MARKER_CONTENT = "eveland-e2e-marker: durable-session-workspace-survives-redeploy\n";
const INITIAL_SEED_CONTENT = "eveland-seed-preserved";
const UPDATED_SEED_CONTENT = "eveland-seed-updated-after-sync";
const SHARED_ENVIRONMENT_KEY = "EVELAND_E2E_SHARED_ENVIRONMENT";
const SHARED_ENVIRONMENT_VALUE = "shared-environment-reaches-systemd";

// A fresh `npx eve build`/`npx eve start` inside the Lima VM (cold npm
// install, no warm caches) is slower than the 15s default health timeout.
process.env.EVELAND_HEALTH_TIMEOUT_MS ??= "30000";

async function pathExists(target: string): Promise<boolean> {
  return await stat(target).then(
    () => true,
    () => false,
  );
}

/**
 * Mirrors jobs/process.ts's own `buildDir` expression. No helper is exported
 * for it (unlike the sandbox cache root/dir, which two call sites inside the
 * worker must agree on) because only one call site ever produces it -- this
 * test is a second, so the join is duplicated deliberately, not extracted.
 */
function releaseDirFor(projectId: string, releaseId: string): string {
  const dataDir = process.env.EVELAND_DATA_DIR ?? ".eveland-data";
  return path.resolve(path.join(dataDir, "builds", projectId, releaseId));
}

/**
 * The deterministic core of this test: proves the *generated* sandbox module
 * resolves to the real bwrap backend on this host and honors
 * EVELAND_SANDBOX_CACHE_DIR, without going through eve's session/runtime
 * APIs at all. Written into the release, then run as root writes it, but
 * executed as the deployment user under the same hardening the deployed
 * unit gets.
 */
function buildCheckScript(): string {
  return `// Generated by agent-sandbox-e2e.ts. Verifies the *generated* sandbox
// module (agent/sandbox/sandbox.js) selects the real bwrap backend on this host and
// honors EVELAND_SANDBOX_CACHE_DIR -- deliberately bypassing eve's own
// session/runtime APIs so this check depends only on @eveland/sandbox-bwrap
// and the generated module, never on eve's model loop.
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const releaseDir = path.dirname(scriptDir); // <releaseDir>/.eveland/<this file>
const sandboxModulePath = path.join(releaseDir, "agent", "sandbox", "sandbox.js");
const sandboxModule = await import(pathToFileURL(sandboxModulePath).href);

const backend = sandboxModule.default.backend();
assert.equal(backend.name, "bwrap", \`expected the bwrap backend, got "\${backend.name}"\`);

const runtimeContext = { appRoot: releaseDir };
const templateKey = ${JSON.stringify(TEMPLATE_KEY)};
const sessionKey = ${JSON.stringify(SESSION_KEY)};
const markerContent = ${JSON.stringify(MARKER_CONTENT)};

await backend.prewarm({ templateKey, runtimeContext, seedFiles: [] });
const handle = await backend.create({ templateKey, sessionKey, runtimeContext });
try {
  const mode = process.env.E2E_CHECK_MODE;
  if (mode === "seed") {
    const result = await handle.session.run({ command: "echo hello-from-sandbox" });
    assert.equal(result.exitCode, 0, \`echo failed: \${result.stderr}\`);
    assert.ok(result.stdout.includes("hello-from-sandbox"), \`unexpected stdout: \${result.stdout}\`);
    await handle.session.writeTextFile({ path: "e2e-marker.txt", content: markerContent });
    const restrict = await handle.session.run({
      command: "chmod 0600 /workspace/e2e-marker.txt && chmod 0700 /workspace",
    });
    assert.equal(restrict.exitCode, 0, \`chmod failed: \${restrict.stderr}\`);
  } else if (mode === "verify") {
    const content = await handle.session.readTextFile({ path: "e2e-marker.txt" });
    assert.equal(content, markerContent, "durable session marker did not survive the redeploy");
    const result = await handle.session.run({ command: "echo still-alive" });
    assert.equal(result.exitCode, 0, \`echo failed: \${result.stderr}\`);
    assert.ok(result.stdout.includes("still-alive"), \`unexpected stdout: \${result.stdout}\`);
  } else {
    throw new Error('E2E_CHECK_MODE must be "seed" or "verify"');
  }
} finally {
  await handle.shutdown();
}
console.log("E2E SANDBOX CHECK OK");
`;
}

/**
 * Runs each deterministic check under a fresh dynamic identity with the
 * deployment access group, group-write umask, and production hardening. Using
 * different identities for seed and verify proves the durable cache remains
 * usable across the UID turnover that restart and cold activation can cause.
 */
function buildCheckArgs(input: { releaseDir: string; cacheDir: string; scriptPath: string; mode: "seed" | "verify" }): string[] {
  const dynamicUser = resolveSystemdDeploymentUser(
    `eveland-sandbox-check-${process.pid}-${input.mode}`,
  );
  return [
    "--wait",
    "--pipe",
    "--collect",
    "--service-type=exec",
    `--property=User=${dynamicUser}`,
    "--property=DynamicUser=yes",
    `--property=Group=${DEPLOY_ACCESS_GROUP}`,
    "--property=UMask=0002",
    "--property=NoNewPrivileges=yes",
    "--property=ProtectSystem=strict",
    "--property=ProtectProc=invisible",
    "--property=PrivateTmp=yes",
    `--property=ReadWritePaths=${input.cacheDir}`,
    `--property=WorkingDirectory=${input.releaseDir}`,
    `--setenv=EVELAND_SANDBOX_CACHE_DIR=${input.cacheDir}`,
    `--setenv=EVELAND_SANDBOX_TEMPLATE_REVISION=${input.releaseDir}`,
    `--setenv=TMPDIR=${input.cacheDir}`,
    `--setenv=E2E_CHECK_MODE=${input.mode}`,
    "node",
    input.scriptPath,
  ];
}

async function runDeterministicCheck(input: { releaseDir: string; cacheDir: string; mode: "seed" | "verify" }): Promise<void> {
  const scriptPath = path.join(input.releaseDir, ".eveland", "e2e-check.mjs");
  await mkdir(path.dirname(scriptPath), { recursive: true });
  await writeFile(scriptPath, buildCheckScript(), "utf8");

  const result = await execa(
    "systemd-run",
    buildCheckArgs({
      releaseDir: input.releaseDir,
      cacheDir: input.cacheDir,
      scriptPath,
      mode: input.mode,
    }),
    { all: true, reject: false },
  );
  const output = result.all ?? "";
  if (result.exitCode !== 0 || !output.includes("E2E SANDBOX CHECK OK")) {
    throw new Error(`Deterministic sandbox check (${input.mode}) failed (exit=${result.exitCode ?? "unknown"}):\n${output}`);
  }
}

/** Finds every `markerName` file directly under a session dir in `cacheDir/sessions/*`. */
async function findSessionMarkers(cacheDir: string, markerName: string): Promise<string[]> {
  const sessionsDir = path.join(cacheDir, "sessions");
  const sessionDirs = await readdir(sessionsDir, { withFileTypes: true }).catch(() => []);
  const found: string[] = [];
  for (const entry of sessionDirs) {
    if (!entry.isDirectory()) continue;
    const candidate = path.join(sessionsDir, entry.name, markerName);
    if (await pathExists(candidate)) found.push(candidate);
  }
  return found;
}

/** Bounded retry budget for `runLiveHttpTurn` -- see its doc comment. */
const HTTP_TURN_MAX_ATTEMPTS = 3;
const HTTP_TURN_RETRY_DELAY_MS = 2_000;

type HttpTurnOutcome =
  | { kind: "success"; detail: string }
  // Looks transient (the unit may still be warming up): worth a retry.
  | { kind: "transient"; detail: string }
  // A real failure -- retrying would only hide a regression.
  | { kind: "fatal"; detail: string };

/**
 * Drives one real agent turn through the deployed HTTP surface (fact 7:
 * EVE_MOCK_AUTHORED_MODELS=1 activates eve's deterministic mock model
 * adapter, so the turn needs no model credentials) and classifies the
 * outcome so `runLiveHttpTurn` knows whether a retry is warranted.
 */
async function runHttpTurnOnce(input: {
  hostPort: number;
  cacheDir: string;
  expectedSeedContent: string;
}): Promise<HttpTurnOutcome> {
  const markerName = "http-turn-marker.txt";
  const message =
    `Use the sandbox-probe skill, then use the bash tool to run the command ` +
    `\`test "$(cat eveland-seed.txt)" = ${JSON.stringify(input.expectedSeedContent)} && ` +
    `echo http-turn-ran > ${markerName}\`.`;

  try {
    const before = new Set(await findSessionMarkers(input.cacheDir, markerName));

    const createResponse = await fetch(`http://127.0.0.1:${input.hostPort}/eve/v1/session`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ message }),
      signal: AbortSignal.timeout(10_000),
    });
    const createBody = await createResponse.text();
    if (!createResponse.ok) {
      return { kind: "transient", detail: `POST /eve/v1/session -> ${createResponse.status}: ${createBody}` };
    }

    let sessionId: string | undefined;
    try {
      const parsed = JSON.parse(createBody) as { sessionId?: unknown };
      sessionId = typeof parsed.sessionId === "string" ? parsed.sessionId : undefined;
    } catch {
      // fall through to the header below
    }
    sessionId ??= createResponse.headers.get("x-eve-session-id") ?? undefined;
    if (!sessionId) {
      return { kind: "transient", detail: `No session id in create response: ${createBody}` };
    }

    const streamUrl = `http://127.0.0.1:${input.hostPort}/eve/v1/session/${encodeURIComponent(sessionId)}/stream`;
    const streamResponse = await fetch(streamUrl, { signal: AbortSignal.timeout(20_000) });
    if (!streamResponse.ok || !streamResponse.body) {
      return { kind: "transient", detail: `GET ${streamUrl} -> ${streamResponse.status}` };
    }

    let raw = "";
    let consumedUpTo = 0;
    let sawCompletion = false;
    let sawFailure = false;
    let sawSkillLoad = false;
    const reader = streamResponse.body.getReader();
    const decoder = new TextDecoder();
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      raw += decoder.decode(value, { stream: true });
      let newlineIndex: number;
      while ((newlineIndex = raw.indexOf("\n", consumedUpTo)) >= 0) {
        const line = raw.slice(consumedUpTo, newlineIndex);
        consumedUpTo = newlineIndex + 1;
        if (!line.trim()) continue;
        try {
          const event = JSON.parse(line) as {
            type?: unknown;
            data?: { actions?: Array<{ kind?: unknown; toolName?: unknown }> };
          };
          // This is a conversational (not task-mode) session: it never emits
          // `session.completed` after a turn, only `turn.completed` followed
          // by `session.waiting` for the next user message (confirmed live
          // against a running deployment -- the docs' abbreviated event list
          // is misleading here). Treat either turn-level signal as done.
          if (event.type === "turn.completed" || event.type === "session.completed") sawCompletion = true;
          if (event.type === "turn.failed") sawFailure = true;
          if (
            event.type === "actions.requested" &&
            event.data?.actions?.some((action) => action.kind === "tool-call" && action.toolName === "load_skill")
          ) {
            sawSkillLoad = true;
          }
        } catch {
          // non-JSON line; ignore for event detection but it stays in `raw` for diagnostics
        }
      }
      if (sawCompletion || sawFailure) break;
    }
    await reader.cancel().catch(() => undefined);

    if (sawFailure) {
      // A definite failure signal from eve's runtime, not an ambiguous
      // connection/timeout problem -- do not retry.
      return { kind: "fatal", detail: `turn.failed observed in the event stream:\n${raw}` };
    }
    if (!sawCompletion) {
      return { kind: "transient", detail: `stream ended without turn.completed within timeout:\n${raw}` };
    }
    if (!sawSkillLoad) {
      return {
        kind: "fatal",
        detail: `turn.completed observed without a load_skill action for sandbox-probe:\n${raw}`,
      };
    }

    const after = await findSessionMarkers(input.cacheDir, markerName);
    const created = after.filter((candidate) => !before.has(candidate));
    if (created.length === 0) {
      // The turn completed but the injected backend was never invoked (or
      // invoked and failed silently) -- a real regression, not a fluke of
      // timing. Retrying would only hide it.
      return {
        kind: "fatal",
        detail: `turn.completed observed, but no new ${markerName} appeared under ${input.cacheDir}/sessions. Stream:\n${raw}`,
      };
    }

    return { kind: "success", detail: `turn completed; marker written at ${created.join(", ")}` };
  } catch (error) {
    // Thrown by fetch/stream on connection-level problems (refused,
    // reset, DNS, abort) -- indistinguishable from the unit still warming
    // up, so treated as transient.
    return { kind: "transient", detail: error instanceof Error ? (error.stack ?? error.message) : String(error) };
  }
}

/**
 * Required: proves eve's deployed .output runtime -- not just the generated
 * module in isolation -- actually invokes the injected bwrap backend for a
 * live turn. The deterministic check above deliberately bypasses eve's own
 * runtime, so this is the only place in the script that exercises the real
 * link between eve's compiled runtime and our generated sandbox module.
 * Throws (rather than returning a soft result) so a regression here fails
 * the whole script and `AGENT SANDBOX E2E OK` is never printed.
 *
 * The deploy unit may still be warming up when this runs, so a transient
 * failure (connection refused, a non-2xx response, or the stream ending
 * with neither turn.completed nor turn.failed) is retried up to
 * HTTP_TURN_MAX_ATTEMPTS times with a short backoff between attempts. A
 * turn that completes but writes no marker, or one that reports
 * turn.failed, is a real failure and is never retried.
 */
async function runLiveHttpTurn(input: {
  hostPort: number;
  cacheDir: string;
  expectedSeedContent: string;
}): Promise<string> {
  const attemptDetails: string[] = [];
  for (let attempt = 1; attempt <= HTTP_TURN_MAX_ATTEMPTS; attempt++) {
    const outcome = await runHttpTurnOnce(input);
    if (outcome.kind === "success") return outcome.detail;
    attemptDetails.push(`attempt ${attempt}/${HTTP_TURN_MAX_ATTEMPTS} (${outcome.kind}): ${outcome.detail}`);
    if (outcome.kind === "fatal") break;
    if (attempt < HTTP_TURN_MAX_ATTEMPTS) await delay(HTTP_TURN_RETRY_DELAY_MS);
  }
  throw new Error(
    `Live HTTP agent turn never proved eve's deployed runtime invokes the injected bwrap backend, after ${attemptDetails.length} attempt(s):\n\n${attemptDetails.join("\n\n")}`,
  );
}

const sourceTempRoot = await mkdtemp(path.join(os.tmpdir(), "eveland-agent-sandbox-source-"));
const syncedSourcePath = path.join(sourceTempRoot, "source");
await materializeEveFixtureDirectory(FIXTURE_SOURCE_PATH, syncedSourcePath);

const { store, close } = await createPgliteTestStore();
const project = await store.createProject({ name: "Agent Sandbox E2E", importKind: "zip", sourcePath: syncedSourcePath });

// So the deployed unit can run a real turn (step C) with no model
// credentials: EVE_MOCK_AUTHORED_MODELS=1 activates eve's deterministic mock
// model adapter (fact 7). Injected the same way any project secret reaches
// the unit's environment -- through the real store/build_deploy pipeline,
// with no code change to systemd.ts needed.
await store.upsertSecret(project.id, "EVE_MOCK_AUTHORED_MODELS", JSON.stringify(encryptSecretValue("1", APP_SECRET_KEY)));
await store.saveSharedAgentEnvironment({
  entries: [{
    key: SHARED_ENVIRONMENT_KEY,
    kind: "secret",
    encryptedValue: JSON.stringify(encryptSecretValue(SHARED_ENVIRONMENT_VALUE, APP_SECRET_KEY)),
  }],
});
let deployment: DeploymentRecord | null = null;

try {
  if (!(await processNextJob(store, "e2e-worker", { appSecretKey: APP_SECRET_KEY }))) {
    throw new Error("import_source job did not run.");
  }
  const imported = await store.getProject(project.id);
  if (imported?.status !== "imported") throw new Error(`Import failed: ${JSON.stringify(imported)}`);

  // --- Deploy 1 --------------------------------------------------------
  await store.enqueueJob(project.id, "build_deploy");
  if (!(await processNextJob(store, "e2e-worker", { appSecretKey: APP_SECRET_KEY }))) {
    throw new Error("build_deploy job did not run (first deploy).");
  }

  const deployedOnce = await store.getProject(project.id);
  deployment = await store.getCurrentDeployment(project.id);
  if (deployedOnce?.deploymentStatus !== "running" || !deployment) {
    const logs = await store.listLogs(project.id, "runtime");
    throw new Error(`First deploy failed: ${JSON.stringify({ deployedOnce, logs })}`);
  }

  const mainPid = (await execa("systemctl", [
    "show",
    "--property=MainPID",
    "--value",
    `${deployment.containerName}.service`,
  ])).stdout.trim();
  assert.match(mainPid, /^[1-9][0-9]*$/, "the deployed systemd unit must have a running MainPID");
  const processEnvironment = (await readFile(`/proc/${mainPid}/environ`, "utf8")).split("\0");
  assert.ok(
    processEnvironment.includes(`${SHARED_ENVIRONMENT_KEY}=${SHARED_ENVIRONMENT_VALUE}`),
    "the project-bound shared Agent environment must reach the real systemd process environment",
  );

  const buildLogs = (await store.listLogs(project.id, "build")).map((log) => log.line).join("\n");
  assert.ok(!buildLogs.includes(SHARED_ENVIRONMENT_VALUE), "the shared environment value must be masked from build logs");
  assert.ok(
    buildLogs.includes("Injected eve sandbox modules: agent/sandbox/sandbox.js"),
    `build log missing the injection line:\n${buildLogs}`,
  );
  assert.ok(
    buildLogs.includes("WARNING: replaced the project's authored sandbox (agent/sandbox/sandbox.ts)"),
    `build log missing the replaced-authored-sandbox warning:\n${buildLogs}`,
  );

  const releaseDir1 = releaseDirFor(project.id, deployment.releaseId);
  assert.ok(
    await pathExists(path.join(releaseDir1, "agent", "sandbox", "sandbox.js")),
    `${releaseDir1}/agent/sandbox/sandbox.js must exist`,
  );
  assert.ok(
    !(await pathExists(path.join(releaseDir1, "agent", "sandbox", "sandbox.ts"))),
    `${releaseDir1}/agent/sandbox/sandbox.ts must NOT exist (the authored module must be removed)`,
  );
  assert.ok(
    await pathExists(path.join(releaseDir1, "agent", "sandbox", "workspace", "eveland-seed.txt")),
    `${releaseDir1}/agent/sandbox/workspace/eveland-seed.txt must be preserved`,
  );
  assert.ok(
    await pathExists(path.join(releaseDir1, ".eveland", "sandbox-bwrap", "index.js")),
    `${releaseDir1}/.eveland/sandbox-bwrap/index.js must exist`,
  );

  const sandboxCacheRoot = resolveSandboxCacheRoot(process.env);
  const projectCacheDir = resolveProjectSandboxCacheDir(sandboxCacheRoot, project.id);

  // --- B.4: deterministic proof the generated module selects OUR backend
  // and honors the cache dir, independent of eve's session API. ----------
  await runDeterministicCheck({ releaseDir: releaseDir1, cacheDir: projectCacheDir, mode: "seed" });
  console.log("Deterministic sandbox check (seed) passed against release 1.");

  // --- C: required live agent turn over HTTP -- the only proof that eve's
  // deployed runtime (not just the generated module in isolation) invokes
  // the injected bwrap backend for a real turn. Throws on failure. --------
  const liveTurnDetail = await runLiveHttpTurn({
    hostPort: deployment.hostPort,
    cacheDir: projectCacheDir,
    expectedSeedContent: INITIAL_SEED_CONTENT,
  });
  console.log(`Eve's deployed runtime invoked the injected bwrap backend for a live turn -- ${liveTurnDetail}`);

  // --- Sync and deploy ---------------------------------------------------
  // Update the imported source's authored workspace, then exercise the same
  // two-job import_source -> build_deploy chain used by the sync actions.
  await writeFile(
    path.join(syncedSourcePath, "agent", "sandbox", "workspace", "eveland-seed.txt"),
    `${UPDATED_SEED_CONTENT}\n`,
    "utf8",
  );

  // build_deploy creates a concurrent immutable preview and deliberately does
  // not replace the current production Deployment. Track the IDs that already
  // exist so the second Release is selected as the newly-created preview,
  // rather than asking getCurrentDeployment() for the still-current first one.
  const deploymentIdsBeforeRedeploy = new Set((await store.listDeployments(project.id)).map((item) => item.id));
  await store.enqueueJob(project.id, "import_source", {
    sourcePath: syncedSourcePath,
    deployAfterImport: true,
  });
  if (!(await processNextJob(store, "e2e-worker", { appSecretKey: APP_SECRET_KEY }))) {
    throw new Error("import_source job did not run (sync and deploy).");
  }
  if (!(await processNextJob(store, "e2e-worker", { appSecretKey: APP_SECRET_KEY }))) {
    throw new Error("build_deploy job did not run (sync and deploy).");
  }

  const deployedTwice = await store.getProject(project.id);
  const newDeployments = (await store.listDeployments(project.id)).filter((item) => !deploymentIdsBeforeRedeploy.has(item.id));
  assert.equal(newDeployments.length, 1, "redeploy must create exactly one concurrent preview Deployment");
  const deployment2 = newDeployments[0];
  if (deployedTwice?.deploymentStatus !== "running" || deployment2?.status !== "running") {
    const logs = await store.listLogs(project.id, "runtime");
    throw new Error(`Redeploy failed: ${JSON.stringify({ deployedTwice, logs })}`);
  }
  deployment = deployment2;

  const releaseDir2 = releaseDirFor(project.id, deployment2.releaseId);
  assert.notEqual(releaseDir2, releaseDir1, "redeploy must produce a new release directory");
  assert.ok(
    await pathExists(path.join(releaseDir2, "agent", "sandbox", "sandbox.js")),
    `${releaseDir2}/agent/sandbox/sandbox.js must exist`,
  );
  assert.equal(
    await readFile(path.join(releaseDir2, "agent", "sandbox", "workspace", "eveland-seed.txt"), "utf8"),
    `${UPDATED_SEED_CONTENT}\n`,
    "the second Release must contain the synced workspace seed",
  );

  const updatedLiveTurnDetail = await runLiveHttpTurn({
    hostPort: deployment2.hostPort,
    cacheDir: projectCacheDir,
    expectedSeedContent: UPDATED_SEED_CONTENT,
  });
  console.log(`A new Session used the synced workspace seed from release 2 -- ${updatedLiveTurnDetail}`);

  // --- Regression proof: the durable session workspace survives the
  // redeploy because the cache dir lives outside the release dir. ---------
  await runDeterministicCheck({ releaseDir: releaseDir2, cacheDir: projectCacheDir, mode: "verify" });
  console.log("Deterministic sandbox check (verify) passed against release 2: durable session survived the redeploy.");

  console.log("AGENT SANDBOX E2E OK");
} finally {
  // Best-effort cleanup covering every exit path. `systemctl` glob-matches
  // unit names, so this sweeps up any `eveland-*` unit left behind by this
  // run even when a health-check timeout left a transient unit running with
  // no deployment record. Wiping units by glob is only safe because this
  // script runs on a dedicated, disposable test VM (see infra/lima) -- do NOT
  // copy this pattern onto a shared or production host, where it would nuke
  // every eveland deployment.
  if (deployment) {
    await execa("systemctl", ["stop", `${deployment.containerName}.service`], { reject: false });
  }
  await execa("systemctl", ["stop", "eveland-*"], { reject: false });
  await execa("systemctl", ["reset-failed", "eveland-*"], { reject: false });

  const sandboxCacheRoot = resolveSandboxCacheRoot(process.env);
  const projectCacheDir = resolveProjectSandboxCacheDir(sandboxCacheRoot, project.id);
  await rm(projectCacheDir, { recursive: true, force: true });
  await rm(sourceTempRoot, { recursive: true, force: true });
  await close();
}
