// End-to-end proof, in the real Lima VM, that an imported eve project gets a
// working bwrap sandbox it never declared, and that a redeploy preserves the
// durable session workspace. Plain tsx script (no vitest) run against the
// real store + processNextJob pipeline with EVELAND_RUNTIME=systemd, exactly
// as systemd-smoke.ts does.
import assert from "node:assert/strict";
import { execa } from "execa";
import { mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createMemoryStore } from "@eveland/api/store";
import type { DeploymentRecord } from "@eveland/api/types";
import { encryptSecretValue } from "@eveland/shared/secrets";
import { processNextJob } from "../jobs/process.js";
import { resolveProjectSandboxCacheDir, resolveSandboxCacheRoot } from "../runtime/systemd.js";

if (process.env.EVELAND_RUNTIME !== "systemd") {
  throw new Error("Run with EVELAND_RUNTIME=systemd (this test exercises the systemd + bwrap sandbox injection path).");
}

// Matches jobs/process.ts's own dev fallback. Passed explicitly to every
// processNextJob call below so secret encryption/decryption never depends on
// an ambient APP_SECRET_KEY the VM shell may or may not have set.
const APP_SECRET_KEY = process.env.APP_SECRET_KEY ?? "eveland-dev-secret-key-000000000";
const DEPLOY_USER = process.env.EVELAND_APP_USER ?? "eveland-app";
const FIXTURE_SOURCE_PATH = fileURLToPath(new URL("./fixtures/agent-sandbox-e2e", import.meta.url));

const TEMPLATE_KEY = "e2e-template";
const SESSION_KEY = "e2e-durable-session";
const MARKER_CONTENT = "eveland-e2e-marker: durable-session-workspace-survives-redeploy\n";

// A fresh `npx eve build`/`npx eve start` inside the Lima VM (cold npm
// install, no warm caches) is slower than the 15s default health timeout.
process.env.EVELAND_HEALTH_TIMEOUT_MS ??= "30000";

async function pathExists(target: string): Promise<boolean> {
  return await stat(target).then(
    () => true,
    () => false,
  );
}

/**
 * Mirrors jobs/process.ts's own `buildDir` expression. No helper is exported
 * for it (unlike the sandbox cache root/dir, which two call sites inside the
 * worker must agree on) because only one call site ever produces it -- this
 * test is a second, so the join is duplicated deliberately, not extracted.
 */
function releaseDirFor(projectId: string, releaseId: string): string {
  const dataDir = process.env.EVELAND_DATA_DIR ?? ".eveland-data";
  return path.resolve(path.join(dataDir, "builds", projectId, releaseId));
}

/**
 * The deterministic core of this test: proves the *generated* sandbox module
 * resolves to the real bwrap backend on this host and honors
 * EVELAND_SANDBOX_CACHE_DIR, without going through eve's session/runtime
 * APIs at all. Written into the release, then run as root writes it, but
 * executed as the deployment user under the same hardening the deployed
 * unit gets.
 */
function buildCheckScript(): string {
  return `// Generated by agent-sandbox-e2e.ts. Verifies the *generated* sandbox
// module (agent/sandbox.js) selects the real bwrap backend on this host and
// honors EVELAND_SANDBOX_CACHE_DIR -- deliberately bypassing eve's own
// session/runtime APIs so this check depends only on @eveland/sandbox-bwrap
// and the generated module, never on eve's model loop.
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const releaseDir = path.dirname(scriptDir); // <releaseDir>/.eveland/<this file>
const sandboxModulePath = path.join(releaseDir, "agent", "sandbox.js");
const sandboxModule = await import(pathToFileURL(sandboxModulePath).href);

const backend = sandboxModule.default.backend();
assert.equal(backend.name, "bwrap", \`expected the bwrap backend, got "\${backend.name}"\`);

const runtimeContext = { appRoot: releaseDir };
const templateKey = ${JSON.stringify(TEMPLATE_KEY)};
const sessionKey = ${JSON.stringify(SESSION_KEY)};
const markerContent = ${JSON.stringify(MARKER_CONTENT)};

await backend.prewarm({ templateKey, runtimeContext, seedFiles: [] });
const handle = await backend.create({ templateKey, sessionKey, runtimeContext });
try {
  const mode = process.env.E2E_CHECK_MODE;
  if (mode === "seed") {
    const result = await handle.session.run({ command: "echo hello-from-sandbox" });
    assert.equal(result.exitCode, 0, \`echo failed: \${result.stderr}\`);
    assert.ok(result.stdout.includes("hello-from-sandbox"), \`unexpected stdout: \${result.stdout}\`);
    await handle.session.writeTextFile({ path: "e2e-marker.txt", content: markerContent });
  } else if (mode === "verify") {
    const content = await handle.session.readTextFile({ path: "e2e-marker.txt" });
    assert.equal(content, markerContent, "durable session marker did not survive the redeploy");
    const result = await handle.session.run({ command: "echo still-alive" });
    assert.equal(result.exitCode, 0, \`echo failed: \${result.stderr}\`);
    assert.ok(result.stdout.includes("still-alive"), \`unexpected stdout: \${result.stdout}\`);
  } else {
    throw new Error('E2E_CHECK_MODE must be "seed" or "verify"');
  }
} finally {
  await handle.shutdown();
}
console.log("E2E SANDBOX CHECK OK");
`;
}

/**
 * systemd-run argv for the check script above. The property list is copied
 * from sandbox-verify.ts's buildSandboxVerifyArgs: same user, same hardening
 * (NoNewPrivileges, ProtectSystem=strict, PrivateTmp), same cache-dir grant
 * and env var -- this check must run under exactly the constraints the
 * deployed unit itself gets, or it proves nothing about the real deployment.
 */
function buildCheckArgs(input: { releaseDir: string; user: string; cacheDir: string; scriptPath: string; mode: "seed" | "verify" }): string[] {
  return [
    "--wait",
    "--pipe",
    "--collect",
    "--service-type=exec",
    `--property=User=${input.user}`,
    "--property=NoNewPrivileges=yes",
    "--property=ProtectSystem=strict",
    "--property=PrivateTmp=yes",
    `--property=ReadWritePaths=${input.cacheDir}`,
    `--property=WorkingDirectory=${input.releaseDir}`,
    `--setenv=EVELAND_SANDBOX_CACHE_DIR=${input.cacheDir}`,
    `--setenv=TMPDIR=${input.cacheDir}`,
    `--setenv=E2E_CHECK_MODE=${input.mode}`,
    "node",
    input.scriptPath,
  ];
}

async function runDeterministicCheck(input: { releaseDir: string; cacheDir: string; mode: "seed" | "verify" }): Promise<void> {
  const scriptPath = path.join(input.releaseDir, ".eveland", "e2e-check.mjs");
  await mkdir(path.dirname(scriptPath), { recursive: true });
  await writeFile(scriptPath, buildCheckScript(), "utf8");

  const result = await execa(
    "systemd-run",
    buildCheckArgs({ releaseDir: input.releaseDir, user: DEPLOY_USER, cacheDir: input.cacheDir, scriptPath, mode: input.mode }),
    { all: true, reject: false },
  );
  const output = result.all ?? "";
  if (result.exitCode !== 0 || !output.includes("E2E SANDBOX CHECK OK")) {
    throw new Error(`Deterministic sandbox check (${input.mode}) failed (exit=${result.exitCode ?? "unknown"}):\n${output}`);
  }
}

/** Finds every `markerName` file directly under a session dir in `cacheDir/sessions/*`. */
async function findSessionMarkers(cacheDir: string, markerName: string): Promise<string[]> {
  const sessionsDir = path.join(cacheDir, "sessions");
  const sessionDirs = await readdir(sessionsDir, { withFileTypes: true }).catch(() => []);
  const found: string[] = [];
  for (const entry of sessionDirs) {
    if (!entry.isDirectory()) continue;
    const candidate = path.join(sessionsDir, entry.name, markerName);
    if (await pathExists(candidate)) found.push(candidate);
  }
  return found;
}

/**
 * Best-effort: drive one real agent turn through the deployed HTTP surface
 * (fact 7: EVE_MOCK_AUTHORED_MODELS=1 activates eve's deterministic mock
 * model adapter, so the turn needs no model credentials). Never throws --
 * returns a result the caller logs, so a failure here never fails the
 * required proof in runDeterministicCheck above.
 */
async function attemptHttpTurn(input: { hostPort: number; cacheDir: string }): Promise<{ ok: boolean; detail: string }> {
  const markerName = "http-turn-marker.txt";
  const message = `Use the bash tool to run the command \`echo http-turn-ran > ${markerName}\`.`;

  try {
    const before = new Set(await findSessionMarkers(input.cacheDir, markerName));

    const createResponse = await fetch(`http://127.0.0.1:${input.hostPort}/eve/v1/session`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ message }),
      signal: AbortSignal.timeout(10_000),
    });
    const createBody = await createResponse.text();
    if (!createResponse.ok) {
      return { ok: false, detail: `POST /eve/v1/session -> ${createResponse.status}: ${createBody}` };
    }

    let sessionId: string | undefined;
    try {
      const parsed = JSON.parse(createBody) as { sessionId?: unknown };
      sessionId = typeof parsed.sessionId === "string" ? parsed.sessionId : undefined;
    } catch {
      // fall through to the header below
    }
    sessionId ??= createResponse.headers.get("x-eve-session-id") ?? undefined;
    if (!sessionId) {
      return { ok: false, detail: `No session id in create response: ${createBody}` };
    }

    const streamUrl = `http://127.0.0.1:${input.hostPort}/eve/v1/session/${encodeURIComponent(sessionId)}/stream`;
    const streamResponse = await fetch(streamUrl, { signal: AbortSignal.timeout(20_000) });
    if (!streamResponse.ok || !streamResponse.body) {
      return { ok: false, detail: `GET ${streamUrl} -> ${streamResponse.status}` };
    }

    let raw = "";
    let consumedUpTo = 0;
    let sawCompletion = false;
    let sawFailure = false;
    const reader = streamResponse.body.getReader();
    const decoder = new TextDecoder();
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      raw += decoder.decode(value, { stream: true });
      let newlineIndex: number;
      while ((newlineIndex = raw.indexOf("\n", consumedUpTo)) >= 0) {
        const line = raw.slice(consumedUpTo, newlineIndex);
        consumedUpTo = newlineIndex + 1;
        if (!line.trim()) continue;
        try {
          const event = JSON.parse(line) as { type?: unknown };
          // This is a conversational (not task-mode) session: it never emits
          // `session.completed` after a turn, only `turn.completed` followed
          // by `session.waiting` for the next user message (confirmed live
          // against a running deployment -- the docs' abbreviated event list
          // is misleading here). Treat either turn-level signal as done.
          if (event.type === "turn.completed" || event.type === "session.completed") sawCompletion = true;
          if (event.type === "turn.failed") sawFailure = true;
        } catch {
          // non-JSON line; ignore for event detection but it stays in `raw` for diagnostics
        }
      }
      if (sawCompletion || sawFailure) break;
    }
    await reader.cancel().catch(() => undefined);

    if (sawFailure) {
      return { ok: false, detail: `turn.failed observed in the event stream:\n${raw}` };
    }
    if (!sawCompletion) {
      return { ok: false, detail: `stream ended without turn.completed within timeout:\n${raw}` };
    }

    const after = await findSessionMarkers(input.cacheDir, markerName);
    const created = after.filter((candidate) => !before.has(candidate));
    if (created.length === 0) {
      return {
        ok: false,
        detail: `turn.completed observed, but no new ${markerName} appeared under ${input.cacheDir}/sessions. Stream:\n${raw}`,
      };
    }

    return { ok: true, detail: `turn completed; marker written at ${created.join(", ")}` };
  } catch (error) {
    return { ok: false, detail: error instanceof Error ? (error.stack ?? error.message) : String(error) };
  }
}

const store = createMemoryStore();
const project = await store.createProject({ name: "Agent Sandbox E2E", importKind: "zip", sourcePath: FIXTURE_SOURCE_PATH });

// So the deployed unit can run a real turn (step C) with no model
// credentials: EVE_MOCK_AUTHORED_MODELS=1 activates eve's deterministic mock
// model adapter (fact 7). Injected the same way any project secret reaches
// the unit's environment -- through the real store/build_deploy pipeline,
// with no code change to systemd.ts needed.
await store.upsertSecret(project.id, "EVE_MOCK_AUTHORED_MODELS", JSON.stringify(encryptSecretValue("1", APP_SECRET_KEY)));

let deployment: DeploymentRecord | null = null;

try {
  if (!(await processNextJob(store, "e2e-worker", { appSecretKey: APP_SECRET_KEY }))) {
    throw new Error("import_source job did not run.");
  }
  const imported = await store.getProject(project.id);
  if (imported?.status !== "imported") throw new Error(`Import failed: ${JSON.stringify(imported)}`);

  // --- Deploy 1 --------------------------------------------------------
  await store.enqueueJob(project.id, "build_deploy");
  if (!(await processNextJob(store, "e2e-worker", { appSecretKey: APP_SECRET_KEY }))) {
    throw new Error("build_deploy job did not run (first deploy).");
  }

  const deployedOnce = await store.getProject(project.id);
  deployment = await store.getCurrentDeployment(project.id);
  if (deployedOnce?.deploymentStatus !== "running" || !deployment) {
    const logs = await store.listLogs(project.id, "runtime");
    throw new Error(`First deploy failed: ${JSON.stringify({ deployedOnce, logs })}`);
  }

  const buildLogs = (await store.listLogs(project.id, "build")).map((log) => log.line).join("\n");
  assert.ok(
    buildLogs.includes("Injected eve sandbox modules: agent/sandbox.js"),
    `build log missing the injection line:\n${buildLogs}`,
  );
  assert.ok(
    buildLogs.includes("WARNING: replaced the project's authored sandbox (agent/sandbox.ts)"),
    `build log missing the replaced-authored-sandbox warning:\n${buildLogs}`,
  );

  const releaseDir1 = releaseDirFor(project.id, deployment.releaseId);
  assert.ok(await pathExists(path.join(releaseDir1, "agent", "sandbox.js")), `${releaseDir1}/agent/sandbox.js must exist`);
  assert.ok(
    !(await pathExists(path.join(releaseDir1, "agent", "sandbox.ts"))),
    `${releaseDir1}/agent/sandbox.ts must NOT exist (the authored module must be removed)`,
  );
  assert.ok(
    await pathExists(path.join(releaseDir1, ".eveland", "sandbox-bwrap", "index.js")),
    `${releaseDir1}/.eveland/sandbox-bwrap/index.js must exist`,
  );

  const sandboxCacheRoot = resolveSandboxCacheRoot(process.env);
  const projectCacheDir = resolveProjectSandboxCacheDir(sandboxCacheRoot, project.id);

  // --- B.4: deterministic proof the generated module selects OUR backend
  // and honors the cache dir, independent of eve's session API. ----------
  await runDeterministicCheck({ releaseDir: releaseDir1, cacheDir: projectCacheDir, mode: "seed" });
  console.log("Deterministic sandbox check (seed) passed against release 1.");

  // --- C: best-effort real agent turn over HTTP (never fails the test) --
  const httpTurn = await attemptHttpTurn({ hostPort: deployment.hostPort, cacheDir: projectCacheDir });
  console.log(`Best-effort HTTP turn: ${httpTurn.ok ? "SUCCEEDED" : "did not complete"} -- ${httpTurn.detail}`);

  // --- Redeploy ----------------------------------------------------------
  await store.enqueueJob(project.id, "build_deploy");
  if (!(await processNextJob(store, "e2e-worker", { appSecretKey: APP_SECRET_KEY }))) {
    throw new Error("build_deploy job did not run (redeploy).");
  }

  const deployedTwice = await store.getProject(project.id);
  const deployment2 = await store.getCurrentDeployment(project.id);
  if (deployedTwice?.deploymentStatus !== "running" || !deployment2) {
    const logs = await store.listLogs(project.id, "runtime");
    throw new Error(`Redeploy failed: ${JSON.stringify({ deployedTwice, logs })}`);
  }
  deployment = deployment2;

  const releaseDir2 = releaseDirFor(project.id, deployment2.releaseId);
  assert.notEqual(releaseDir2, releaseDir1, "redeploy must produce a new release directory");
  assert.ok(await pathExists(path.join(releaseDir2, "agent", "sandbox.js")), `${releaseDir2}/agent/sandbox.js must exist`);

  // --- Regression proof: the durable session workspace survives the
  // redeploy because the cache dir lives outside the release dir. ---------
  await runDeterministicCheck({ releaseDir: releaseDir2, cacheDir: projectCacheDir, mode: "verify" });
  console.log("Deterministic sandbox check (verify) passed against release 2: durable session survived the redeploy.");

  console.log("AGENT SANDBOX E2E OK");
} finally {
  // Best-effort cleanup covering every exit path. `systemctl` glob-matches
  // unit names, so this sweeps up any `eveland-*` unit left behind by this
  // run even when a health-check timeout left a transient unit running with
  // no deployment record. Wiping units by glob is only safe because this
  // script runs on a dedicated, disposable test VM (see infra/lima) -- do NOT
  // copy this pattern onto a shared or production host, where it would nuke
  // every eveland deployment.
  if (deployment) {
    await execa("systemctl", ["stop", `${deployment.containerName}.service`], { reject: false });
  }
  await execa("systemctl", ["stop", "eveland-*"], { reject: false });
  await execa("systemctl", ["reset-failed", "eveland-*"], { reject: false });

  const sandboxCacheRoot = resolveSandboxCacheRoot(process.env);
  const projectCacheDir = resolveProjectSandboxCacheDir(sandboxCacheRoot, project.id);
  await rm(projectCacheDir, { recursive: true, force: true });
}
