import { execa } from "execa";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { SANDBOX_TOOLCHAIN_COMMANDS } from "./sandbox-toolchain.js";

/**
 * Relative to `releaseDir`. Lives alongside `VENDORED_BACKEND_DIR`
 * (`.eveland/sandbox-bwrap/`, see sandbox-inject.ts) so the generated
 * script's `./sandbox-bwrap/index.js` import resolves as a sibling.
 */
export const SANDBOX_VERIFY_SCRIPT_PATH = ".eveland/verify-sandbox.mjs";

/**
 * Builds the throwaway script that exercises the real vendored bwrap backend:
 * prewarm -> create -> run -> shutdown against a scratch app root inside the
 * project's sandbox cache dir. `eve build` never calls `prewarm` on a
 * self-hosted release and `/eve/v1/health` returns 200 regardless of sandbox
 * health (both confirmed against eve 0.29.5), so this is the only point in
 * the pipeline that can catch a host that cannot run bwrap.
 */
export function buildSandboxVerifyScript(): string {
  const toolchainCommands = SANDBOX_TOOLCHAIN_COMMANDS.join(" ");
  return `// Generated by eveland. Verifies the vendored sandbox backend on this host.
import { mkdtemp, rm } from "node:fs/promises";
import path from "node:path";
// This script lives at <releaseDir>/.eveland/verify-sandbox.mjs, so the
// vendored backend is its sibling.
import { createBwrapSandboxBackend } from "./sandbox-bwrap/index.js";

// Setting the exit code field (rather than forcing an immediate exit) lets
// the process drain its stdout/stderr pipes naturally before it exits. stdout
// and stderr are pipes here (execa's { all: true } upstream, and systemd-run's
// --pipe), and forcing an exit can truncate a large diagnostic still sitting
// in those pipe buffers.
function fail(message) {
  console.error(\`sandbox self-check failed: \${message}\`);
  process.exitCode = 1;
}

const cacheRoot = process.env.EVELAND_SANDBOX_CACHE_DIR;
if (!cacheRoot) {
  fail("EVELAND_SANDBOX_CACHE_DIR is not set");
} else {
  // Declared outside the try so the finally block can still clean up a
  // partially-created appRoot if mkdtemp itself is what throws.
  let appRoot;
  try {
    appRoot = await mkdtemp(path.join(cacheRoot, "verify-"));
    const backend = createBwrapSandboxBackend();
    const runtimeContext = { appRoot };
    await backend.prewarm({ templateKey: "eveland-verify", runtimeContext, seedFiles: [] });
    const handle = await backend.create({ templateKey: "eveland-verify", sessionKey: "eveland-verify", runtimeContext });
    await handle.session.writeTextFile({
      path: "eveland-verify.ts",
      content: 'const message: string = "eveland-typescript-ok";\\nconsole.log(message);\\n',
    });
    const typeScriptResult = await handle.session.run({ command: "node eveland-verify.ts" });
    const toolchainCommand = \`set -eu
missing=""
for command in ${toolchainCommands}; do
  if ! command -v "$command" >/dev/null 2>&1; then missing="$missing $command"; fi
done
if [ -n "$missing" ]; then
  echo "missing sandbox commands:$missing" >&2
  exit 127
fi
npm --version >/dev/null
pnpm --version >/dev/null
rg -n --color=never -i -m 1 -- 'eveland-typescript-ok' . >/dev/null
grep -r -n --color=never --exclude-dir=.git -i -E -m 1 -- 'eveland-typescript-ok' . >/dev/null
find . -type f -name eveland-verify.ts -print | grep -q .
git --version >/dev/null
curl --version >/dev/null
jq -n -e '{"ok": true} | .ok' >/dev/null
python -c 'import sys; assert sys.version_info >= (3, 10)'
python3 -c 'import sys; assert sys.version_info >= (3, 10)'
pip --version >/dev/null
pip3 --version >/dev/null
unzip -v >/dev/null
test "$(printf eveland-zstd-ok | zstd -q -c | zstd -q -d -c)" = "eveland-zstd-ok"\`;
    const toolchainResult = await handle.session.run({ command: toolchainCommand });
    await handle.shutdown();
    const failures = [];
    if (typeScriptResult.exitCode !== 0 || !typeScriptResult.stdout.includes("eveland-typescript-ok")) {
      failures.push(\`TypeScript probe: exit=\${typeScriptResult.exitCode} stdout=\${typeScriptResult.stdout} stderr=\${typeScriptResult.stderr}\`);
    }
    if (toolchainResult.exitCode !== 0) {
      failures.push(\`sandbox toolchain probe: exit=\${toolchainResult.exitCode} stdout=\${toolchainResult.stdout} stderr=\${toolchainResult.stderr}\`);
    }
    if (failures.length > 0) {
      fail(failures.join("\\n"));
    } else {
      console.log("SANDBOX VERIFY OK");
    }
  } catch (error) {
    // prewarm()/create()/shutdown() throwing is the real path for both named
    // host-prerequisite failures (missing AppArmor profile, missing
    // /workspace) -- without this catch, that throw would propagate past this
    // script entirely as an uncaught exception, printing a raw Node stack
    // trace instead of the same structured diagnostic every other failure
    // path here produces.
    fail(error instanceof Error ? (error.stack ?? error.message) : String(error));
  } finally {
    if (appRoot) {
      await rm(appRoot, { force: true, recursive: true });
    }
  }
}
`;
}

export type SandboxVerifyArgsInput = {
  releaseDir: string;
  user: string;
  cacheDir: string;
};

/**
 * `systemd-run` argv that runs the verify script as the deployment user
 * under the same hardening (`NoNewPrivileges`, `ProtectSystem=strict`,
 * `PrivateTmp`) the running service gets. `--wait --pipe` blocks until the
 * unit exits and streams its stdout/stderr back to this process so
 * `verifySandbox` can inspect both the exit code and the success marker.
 */
export function buildSandboxVerifyArgs(input: SandboxVerifyArgsInput): string[] {
  return [
    "--wait",
    "--pipe",
    "--collect",
    "--service-type=exec",
    `--property=User=${input.user}`,
    "--property=NoNewPrivileges=yes",
    "--property=ProtectSystem=strict",
    "--property=PrivateTmp=yes",
    `--property=ReadWritePaths=${input.cacheDir}`,
    `--property=WorkingDirectory=${input.releaseDir}`,
    `--setenv=EVELAND_SANDBOX_CACHE_DIR=${input.cacheDir}`,
    `--setenv=TMPDIR=${input.cacheDir}`,
    "node",
    path.join(input.releaseDir, SANDBOX_VERIFY_SCRIPT_PATH),
  ];
}

export type VerifySandboxInput = {
  releaseDir: string;
  user: string;
  cacheDir: string;
};

export async function writeSandboxVerifyScript(releaseDir: string): Promise<string> {
  const scriptPath = path.join(releaseDir, SANDBOX_VERIFY_SCRIPT_PATH);
  await mkdir(path.dirname(scriptPath), { recursive: true });
  await writeFile(scriptPath, buildSandboxVerifyScript(), "utf8");
  return scriptPath;
}

/**
 * Writes the verify script into the release and runs it under systemd-run,
 * as the deployment user, with the same hardening the deployed service gets.
 * Throws when the check fails for any reason -- non-zero exit OR a missing
 * success marker on exit 0, since a script that silently no-ops is not a
 * passing check -- so a broken sandbox fails the build instead of a later
 * agent turn.
 */
export async function verifySandbox(input: VerifySandboxInput): Promise<void> {
  await writeSandboxVerifyScript(input.releaseDir);

  const result = await execa("systemd-run", buildSandboxVerifyArgs(input), {
    all: true,
    reject: false,
  });
  const output = result.all ?? "";
  if (result.exitCode !== 0 || !output.includes("SANDBOX VERIFY OK")) {
    throw new Error(
      "Sandbox self-check failed: the vendored bwrap backend could not run under this host's deployment " +
        "hardening. Check these host prerequisites:\n" +
        "  1. /etc/apparmor.d/bwrap must exist and grant `userns`. Ubuntu's apt bubblewrap ships no AppArmor " +
        "profile, and kernel.apparmor_restrict_unprivileged_userns=1 then blocks non-root bwrap with " +
        '"setting up uid map: Permission denied".\n' +
        "  2. /workspace must already exist as an empty directory. bwrap cannot create that bind destination " +
        "itself because the host root is bind-mounted read-only first.\n" +
        "  3. The platform-owned sandbox toolchain must be installed on the host: " +
        SANDBOX_TOOLCHAIN_COMMANDS.join(", ") +
        ". The worker preflight reports every missing command.\n" +
        `Captured output (exit=${result.exitCode ?? "unknown"}):\n${output}`,
    );
  }
}
