import { cp, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/** Where the built backend is vendored inside the release directory. */
export const VENDORED_BACKEND_DIR = ".eveland/sandbox-bwrap";

/** Extensions eve accepts for an authored module, highest resolution priority first. */
const AUTHORED_MODULE_EXTENSIONS = [".cts", ".mts", ".cjs", ".mjs", ".ts", ".js"] as const;

export type SandboxInjectionInput = {
  releaseDir: string;
  /** Directory holding the built @eveland/sandbox-bwrap (its dist/). */
  backendDistDir: string;
};

export type SandboxInjectionResult = {
  /** Paths (relative to releaseDir) of generated sandbox modules. */
  generated: string[];
  /** Paths (relative to releaseDir) of authored sandbox modules that were replaced. */
  replaced: string[];
};

export function buildGeneratedSandboxModule(relativeImportPath: string): string {
  return `// Generated by eveland at build time. Do not edit.
// The deploy host decides the sandbox backend; agent projects never declare one.
import { defineSandbox, defaultBackend } from "eve/sandbox";
import { bwrap, isBwrapAvailable } from "${relativeImportPath}";

const cacheDir = process.env.EVELAND_SANDBOX_CACHE_DIR;

export default defineSandbox({
  backend: () => (isBwrapAvailable() ? bwrap(cacheDir ? { cacheDir } : {}) : defaultBackend()),
});
`;
}

async function listDirectories(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
}

async function pathKind(target: string): Promise<"file" | "directory" | null> {
  const entries = await readdir(path.dirname(target), { withFileTypes: true }).catch(() => []);
  const match = entries.find((entry) => entry.name === path.basename(target));
  if (!match) return null;
  return match.isDirectory() ? "directory" : "file";
}

/**
 * Every directory that owns a sandbox: the agent root plus each subagent.
 *
 * eve resolves subagents from `agent/subagents/<name>/` (confirmed against
 * eve 0.22.1's `discoverSubagents`, which defaults `subagentsDirectoryPath`
 * to `join(agentRoot, "subagents")`). Nested subagents-of-subagents are not
 * walked here: eve does support them recursively, but this generator only
 * targets the one level the brief and its tests cover.
 */
export async function resolveSandboxRoots(releaseDir: string): Promise<string[]> {
  const agentDir = path.join(releaseDir, "agent");
  if ((await pathKind(agentDir)) !== "directory") return [];
  const roots = ["agent"];
  for (const name of await listDirectories(path.join(agentDir, "subagents"))) {
    roots.push(path.posix.join("agent", "subagents", name));
  }
  return roots;
}

export async function injectSandboxModules(input: SandboxInjectionInput): Promise<SandboxInjectionResult> {
  const roots = await resolveSandboxRoots(input.releaseDir);
  const generated: string[] = [];
  const replaced: string[] = [];
  if (roots.length === 0) return { generated, replaced };

  const vendorDir = path.join(input.releaseDir, VENDORED_BACKEND_DIR);
  await rm(vendorDir, { force: true, recursive: true });
  await mkdir(path.dirname(vendorDir), { recursive: true });
  await cp(input.backendDistDir, vendorDir, { recursive: true });

  for (const root of roots) {
    const rootDir = path.join(input.releaseDir, root);

    // eve resolves `sandbox/` before `sandbox.<ext>`, and `.ts` before `.js`.
    // Remove every authored form so the generated module is the only match.
    const sandboxDir = path.join(rootDir, "sandbox");
    if ((await pathKind(sandboxDir)) === "directory") {
      await rm(sandboxDir, { force: true, recursive: true });
      replaced.push(path.posix.join(root, "sandbox"));
    }
    for (const extension of AUTHORED_MODULE_EXTENSIONS) {
      const authored = path.join(rootDir, `sandbox${extension}`);
      if ((await pathKind(authored)) === "file") {
        await rm(authored, { force: true });
        replaced.push(path.posix.join(root, `sandbox${extension}`));
      }
    }

    const importPath = path.posix.join(
      path.posix.relative(root, ""),
      VENDORED_BACKEND_DIR,
      "index.js",
    );
    await writeFile(path.join(rootDir, "sandbox.js"), buildGeneratedSandboxModule(importPath), "utf8");
    generated.push(path.posix.join(root, "sandbox.js"));
  }

  return { generated, replaced };
}
