import { execa } from "execa";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Relative to `releaseDir`. Lives alongside `VENDORED_BACKEND_DIR`
 * (`.eveland/sandbox-bwrap/`, see sandbox-inject.ts) so the generated
 * script's `./sandbox-bwrap/index.js` import resolves as a sibling.
 */
export const SANDBOX_VERIFY_SCRIPT_PATH = ".eveland/verify-sandbox.mjs";

/**
 * Builds the throwaway script that exercises the real vendored bwrap backend:
 * prewarm -> create -> run -> shutdown against a scratch app root inside the
 * project's sandbox cache dir. `eve build` never calls `prewarm` on a
 * self-hosted release and `/eve/v1/health` returns 200 regardless of sandbox
 * health (both confirmed against eve 0.22.1), so this is the only point in
 * the pipeline that can catch a host that cannot run bwrap.
 */
export function buildSandboxVerifyScript(): string {
  return `// Generated by eveland. Verifies the vendored sandbox backend on this host.
import { mkdtemp, rm } from "node:fs/promises";
import path from "node:path";
// This script lives at <releaseDir>/.eveland/verify-sandbox.mjs, so the
// vendored backend is its sibling.
import { createBwrapSandboxBackend } from "./sandbox-bwrap/index.js";

const cacheRoot = process.env.EVELAND_SANDBOX_CACHE_DIR;
if (!cacheRoot) {
  console.error("EVELAND_SANDBOX_CACHE_DIR is not set");
  process.exit(1);
}

const appRoot = await mkdtemp(path.join(cacheRoot, "verify-"));
try {
  const backend = createBwrapSandboxBackend();
  const runtimeContext = { appRoot };
  await backend.prewarm({ templateKey: "eveland-verify", runtimeContext, seedFiles: [] });
  const handle = await backend.create({ templateKey: "eveland-verify", sessionKey: "eveland-verify", runtimeContext });
  const result = await handle.session.run({ command: "echo eveland-sandbox-ok" });
  await handle.shutdown();
  if (result.exitCode !== 0 || !result.stdout.includes("eveland-sandbox-ok")) {
    console.error(\`sandbox self-check failed: exit=\${result.exitCode} stdout=\${result.stdout} stderr=\${result.stderr}\`);
    process.exit(1);
  }
  console.log("SANDBOX VERIFY OK");
} finally {
  await rm(appRoot, { force: true, recursive: true });
}
`;
}

export type SandboxVerifyArgsInput = {
  releaseDir: string;
  user: string;
  cacheDir: string;
};

/**
 * `systemd-run` argv that runs the verify script as the deployment user
 * under the same hardening (`NoNewPrivileges`, `ProtectSystem=strict`,
 * `PrivateTmp`) the running service gets. `--wait --pipe` blocks until the
 * unit exits and streams its stdout/stderr back to this process so
 * `verifySandbox` can inspect both the exit code and the success marker.
 */
export function buildSandboxVerifyArgs(input: SandboxVerifyArgsInput): string[] {
  return [
    "--wait",
    "--pipe",
    "--collect",
    "--service-type=exec",
    `--property=User=${input.user}`,
    "--property=NoNewPrivileges=yes",
    "--property=ProtectSystem=strict",
    "--property=PrivateTmp=yes",
    `--property=ReadWritePaths=${input.cacheDir}`,
    `--property=WorkingDirectory=${input.releaseDir}`,
    `--setenv=EVELAND_SANDBOX_CACHE_DIR=${input.cacheDir}`,
    `--setenv=TMPDIR=${input.cacheDir}`,
    "node",
    path.join(input.releaseDir, SANDBOX_VERIFY_SCRIPT_PATH),
  ];
}

export type VerifySandboxInput = {
  releaseDir: string;
  user: string;
  cacheDir: string;
};

/**
 * Writes the verify script into the release and runs it under systemd-run,
 * as the deployment user, with the same hardening the deployed service gets.
 * Throws when the check fails for any reason -- non-zero exit OR a missing
 * success marker on exit 0, since a script that silently no-ops is not a
 * passing check -- so a broken sandbox fails the build instead of a later
 * agent turn.
 */
export async function verifySandbox(input: VerifySandboxInput): Promise<void> {
  const scriptPath = path.join(input.releaseDir, SANDBOX_VERIFY_SCRIPT_PATH);
  await mkdir(path.dirname(scriptPath), { recursive: true });
  await writeFile(scriptPath, buildSandboxVerifyScript(), "utf8");

  const result = await execa("systemd-run", buildSandboxVerifyArgs(input), { all: true, reject: false });
  const output = result.all ?? "";
  if (result.exitCode !== 0 || !output.includes("SANDBOX VERIFY OK")) {
    throw new Error(
      "Sandbox self-check failed: the vendored bwrap backend could not run under this host's deployment " +
        "hardening. This is almost always one of two missing host prerequisites:\n" +
        "  1. /etc/apparmor.d/bwrap must exist and grant `userns`. Ubuntu's apt bubblewrap ships no AppArmor " +
        "profile, and kernel.apparmor_restrict_unprivileged_userns=1 then blocks non-root bwrap with " +
        '"setting up uid map: Permission denied".\n' +
        "  2. /workspace must already exist as an empty directory. bwrap cannot create that bind destination " +
        "itself because the host root is bind-mounted read-only first.\n" +
        `Captured output (exit=${result.exitCode ?? "unknown"}):\n${output}`,
    );
  }
}
