import { describe, expect, test } from "vitest";
import {
  buildGeneratedProviderSandboxModule,
  buildPlatformSandboxModule,
  buildSandboxShimModule,
  rewriteEveSandboxImports,
  SHIMMED_SANDBOX_ENTRY_POINTS,
  type ShimmedSandboxEntryPoint,
} from "./sandbox-provider-modules.js";

const MARKER = "// Generated by eveland at build time.";
const shimPath = (entryPoint: ShimmedSandboxEntryPoint) => `../.eveland/shim/${entryPoint}.js`;

describe("buildPlatformSandboxModule", () => {
  test("builds bwrap environments from platform variables and the authored preparation only", () => {
    const source = buildPlatformSandboxModule(MARKER);

    expect(source.startsWith(MARKER)).toBe(true);
    expect(source).toContain('import { BwrapSandbox } from "../sandbox-bwrap/provider.js"');
    for (const variable of [
      "EVELAND_SANDBOX_CACHE_DIR",
      "EVELAND_SANDBOX_RUN_TIMEOUT_MS",
      "EVELAND_SANDBOX_MAX_CONCURRENT_PROCESSES",
      "EVELAND_SANDBOX_MAX_OUTPUT_BYTES",
    ]) {
      expect(source).toContain(`process.env.${variable}`);
    }
    // Templates are keyed by eve's source revision now; the deployment
    // revision the backend used has no meaning for the provider.
    expect(source).not.toContain("EVELAND_SANDBOX_TEMPLATE_REVISION");
    expect(source).toContain("export function platformEnvironment(prepare)");
  });
});

describe("buildSandboxShimModule", () => {
  test.each(Object.keys(SHIMMED_SANDBOX_ENTRY_POINTS) as ShimmedSandboxEntryPoint[])(
    "re-exports %s and shadows its provider with the platform environment",
    (entryPoint) => {
      const { specifier, provider, factories } = SHIMMED_SANDBOX_ENTRY_POINTS[entryPoint];
      const source = buildSandboxShimModule(entryPoint, MARKER);

      expect(source.startsWith(MARKER)).toBe(true);
      expect(source).toContain(`export * from "${specifier}";`);
      expect(source).toContain(`export const ${provider} = {`);
      for (const factory of factories) {
        expect(source).toContain(`${factory}: (`);
      }
      expect(source.match(/platformEnvironment\(options\?\.prepare\)/g)).toHaveLength(
        factories.length,
      );
    },
  );

  test("keeps an image factory's options argument in second position", () => {
    expect(buildSandboxShimModule("docker", MARKER)).toContain(
      "image: (_reference, options) => platformEnvironment(options?.prepare),",
    );
  });
});

describe("buildGeneratedProviderSandboxModule", () => {
  test("exports the platform environment and a selector that opens it", () => {
    const source = buildGeneratedProviderSandboxModule(
      "../.eveland/sandbox-platform/platform.js",
      MARKER,
    );

    expect(source.startsWith(MARKER)).toBe(true);
    expect(source).toContain('import { defineSandbox } from "eve/sandbox";');
    expect(source).toContain(
      'import { platformEnvironment } from "../.eveland/sandbox-platform/platform.js";',
    );
    expect(source).toContain("export const environment = platformEnvironment();");
    expect(source).toContain("export default defineSandbox(() => environment.open());");
  });
});

describe("rewriteEveSandboxImports", () => {
  test("redirects static, dynamic, re-export, and CommonJS imports of every shimmed entry point", () => {
    const source = [
      'import { defineSandbox, DefaultSandbox } from "eve/sandbox";',
      "import { DockerSandbox } from 'eve/sandbox/docker';",
      'import type { SandboxSession } from "eve/sandbox";',
      'export { VercelSandbox } from "eve/sandbox/vercel";',
      'const lazy = await import("eve/sandbox/microsandbox");',
      'const { JustBashSandbox } = require("eve/sandbox/just-bash");',
    ].join("\n");

    const result = rewriteEveSandboxImports(source, shimPath);

    expect(result.rewritten).toBe(6);
    expect(result.source).toBe(
      [
        'import { defineSandbox, DefaultSandbox } from "../.eveland/shim/sandbox.js";',
        "import { DockerSandbox } from '../.eveland/shim/docker.js';",
        'import type { SandboxSession } from "../.eveland/shim/sandbox.js";',
        'export { VercelSandbox } from "../.eveland/shim/vercel.js";',
        'const lazy = await import("../.eveland/shim/microsandbox.js");',
        'const { JustBashSandbox } = require("../.eveland/shim/just-bash.js");',
      ].join("\n"),
    );
  });

  test("leaves custom providers, other eve modules, and lookalike specifiers alone", () => {
    const source = [
      'import { defineSandboxProvider } from "eve/sandbox/provider";',
      'import { defineTool } from "eve/tools";',
      'import { helper } from "eve/sandboxes";',
      'import { other } from "not-eve/sandbox";',
      'const text = "eve/sandbox is just a string here";',
    ].join("\n");

    expect(rewriteEveSandboxImports(source, shimPath)).toEqual({ source, rewritten: 0 });
  });

  test("is idempotent: rewritten source has nothing left to rewrite", () => {
    const once = rewriteEveSandboxImports(
      'import { DefaultSandbox } from "eve/sandbox";',
      shimPath,
    );

    expect(rewriteEveSandboxImports(once.source, shimPath)).toEqual({
      source: once.source,
      rewritten: 0,
    });
  });
});
