import { access, cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  buildGeneratedProviderSandboxModule,
  buildPlatformSandboxModule,
  buildSandboxShimModule,
  rewriteEveSandboxImports,
  SANDBOX_PLATFORM_DIR,
  SHIMMED_SANDBOX_ENTRY_POINTS,
  type ShimmedSandboxEntryPoint,
} from "./sandbox-provider-modules.js";

/**
 * Where the built @evelandhq/sandbox-bwrap package is vendored inside the
 * release directory. The platform module imports its provider entry point.
 */
export const VENDORED_BACKEND_DIR = ".eveland/sandbox-bwrap";

/** Extensions eve accepts for an authored module, highest resolution priority first. */
const AUTHORED_MODULE_EXTENSIONS = [".cts", ".mts", ".cjs", ".mjs", ".ts", ".js"] as const;

/**
 * First line of every module this file generates. `.js` is both an authored
 * module extension eve resolves and the extension we always write, so a
 * re-run must tell its own previous output apart from a project's authored
 * `sandbox.js` by content, not by path. Exported so the module builders and
 * the removal loops can never drift apart.
 */
export const GENERATED_MODULE_MARKER = "// Generated by eveland at build time.";

export type SandboxInjectionInput = {
  releaseDir: string;
  /** Directory holding the built @evelandhq/sandbox-bwrap (its dist/). */
  backendDistDir: string;
};

export type SandboxInjectionResult = {
  /** Paths (relative to releaseDir) of generated sandbox modules. */
  generated: string[];
  /** Authored modules kept in place with their eve sandbox imports redirected. */
  rewritten: string[];
  /** Paths (relative to releaseDir) of authored sandbox modules that were replaced. */
  replaced: string[];
};

export function resolveSandboxRunTimeoutMs(env: NodeJS.ProcessEnv): string {
  const value = Number(env.EVELAND_SANDBOX_RUN_TIMEOUT_MS ?? 600_000);
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error("EVELAND_SANDBOX_RUN_TIMEOUT_MS must be a positive safe integer.");
  }
  return String(value);
}

function resolvePositiveSandboxInteger(
  env: NodeJS.ProcessEnv,
  name: string,
  fallback: number,
): string {
  const value = Number(env[name] ?? fallback);
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${name} must be a positive safe integer.`);
  }
  return String(value);
}

export function resolveSandboxProcessLimits(env: NodeJS.ProcessEnv): {
  maxConcurrentProcesses: string;
  maxOutputBytes: string;
} {
  return {
    maxConcurrentProcesses: resolvePositiveSandboxInteger(
      env,
      "EVELAND_SANDBOX_MAX_CONCURRENT_PROCESSES",
      64,
    ),
    maxOutputBytes: resolvePositiveSandboxInteger(
      env,
      "EVELAND_SANDBOX_MAX_OUTPUT_BYTES",
      16 * 1024 * 1024,
    ),
  };
}

async function listDirectories(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
}

async function pathKind(target: string): Promise<"file" | "directory" | "other" | null> {
  const entries = await readdir(path.dirname(target), { withFileTypes: true }).catch(() => []);
  const match = entries.find((entry) => entry.name === path.basename(target));
  if (!match) return null;
  if (match.isDirectory()) return "directory";
  if (match.isFile()) return "file";
  return "other";
}

async function removeAuthoredSandboxModules(
  moduleDir: string,
  relativeDir: string,
): Promise<string[]> {
  const removed: string[] = [];
  for (const extension of AUTHORED_MODULE_EXTENSIONS) {
    const authored = path.join(moduleDir, `sandbox${extension}`);
    const kind = await pathKind(authored);
    if (kind === "other") {
      await rm(authored, { force: true, recursive: true });
      removed.push(path.posix.join(relativeDir, `sandbox${extension}`));
      continue;
    }
    if (kind !== "file") continue;

    const contents = await readFile(authored, "utf8").catch(() => "");
    await rm(authored, { force: true });
    // `.js` is both an authored extension and what eveland generates. A re-run
    // must not report its own previous output as authored behavior it replaced.
    if (extension !== ".js" || !contents.startsWith(GENERATED_MODULE_MARKER)) {
      removed.push(path.posix.join(relativeDir, `sandbox${extension}`));
    }
  }
  return removed;
}

/**
 * Every directory that owns a sandbox: the agent root plus every subagent,
 * however deeply nested.
 *
 * eve resolves subagents from `agent/subagents/<name>/` (confirmed against
 * eve 0.29.5's `discoverSubagents`, which defaults `subagentsDirectoryPath`
 * to `join(agentRoot, "subagents")`). `discoverLocalSubagentPackage` then
 * calls `discoverSandboxSource({ rootPath: subagentRoot })` *and*
 * `discoverSubagents({ agentRoot: subagentRoot })` for each directory-form
 * subagent it finds, so subagents can themselves declare further subagents
 * at `<subagentRoot>/subagents/<name>/`, arbitrarily deep — each level owns
 * its own sandbox slot. Only directory-form subagents own a sandbox (a
 * file-form subagent like `subagents/foo.ts` does not), so we only recurse
 * into directory children.
 */
async function collectSandboxRoots(
  releaseDir: string,
  root: string,
  roots: string[],
): Promise<void> {
  roots.push(root);
  const subagentsDir = path.join(releaseDir, root, "subagents");
  for (const name of await listDirectories(subagentsDir)) {
    await collectSandboxRoots(releaseDir, path.posix.join(root, "subagents", name), roots);
  }
}

export async function resolveSandboxRoots(releaseDir: string): Promise<string[]> {
  const agentDir = path.join(releaseDir, "agent");
  if ((await pathKind(agentDir)) !== "directory") return [];
  const roots: string[] = [];
  await collectSandboxRoots(releaseDir, "agent", roots);
  return roots;
}

export async function injectSandboxModules(
  input: SandboxInjectionInput,
): Promise<SandboxInjectionResult> {
  const roots = await resolveSandboxRoots(input.releaseDir);

  // Vendoring is a host-capability concern -- it must happen for every release
  // regardless of project layout, so `verifySandbox` (which imports the
  // vendored backend as a sibling module) always has something to import, even
  // when this project has no agent/ directory and therefore generates no
  // sandbox module below.
  const backendEntryPoint = path.join(input.backendDistDir, "index.js");
  const backendIsBuilt = await access(backendEntryPoint).then(
    () => true,
    () => false,
  );
  if (!backendIsBuilt) {
    throw new Error(
      `@evelandhq/sandbox-bwrap backend is unusable: ${input.backendDistDir} has no index.js. ` +
        "The package ships prebuilt, so this means an incomplete install. Run `pnpm install`, then retry.",
    );
  }
  if ((await pathKind(path.join(input.backendDistDir, "provider.js"))) === null) {
    throw new Error(
      `@evelandhq/sandbox-bwrap at ${input.backendDistDir} has no provider.js, which Eve ` +
        `0.64 and later need. Install @evelandhq/sandbox-bwrap 0.4.0 or newer, then retry.`,
    );
  }

  const vendorDir = path.join(input.releaseDir, VENDORED_BACKEND_DIR);
  await rm(vendorDir, { force: true, recursive: true });
  await mkdir(path.dirname(vendorDir), { recursive: true });
  await cp(input.backendDistDir, vendorDir, { recursive: true });

  return await injectProviderModules(input.releaseDir, roots);
}

/**
 * Eve's provider-environment sandbox shape, which every supported line
 * compiles. Every slot ends up with exactly one module eve loads: the
 * authored one, kept in place with its eve sandbox imports redirected to the
 * platform shims, or a generated one when the project left the slot empty. A
 * kept module needs no companion file, because redirecting its imports is
 * enough to put its environment on the platform provider.
 */
async function injectProviderModules(
  releaseDir: string,
  roots: string[],
): Promise<SandboxInjectionResult> {
  const generated: string[] = [];
  const rewritten: string[] = [];
  const replaced: string[] = [];

  const platformDir = path.join(releaseDir, SANDBOX_PLATFORM_DIR);
  await rm(platformDir, { force: true, recursive: true });
  await mkdir(platformDir, { recursive: true });
  await writeFile(
    path.join(platformDir, "platform.js"),
    buildPlatformSandboxModule(GENERATED_MODULE_MARKER),
    "utf8",
  );
  for (const entryPoint of Object.keys(
    SHIMMED_SANDBOX_ENTRY_POINTS,
  ) as ShimmedSandboxEntryPoint[]) {
    await writeFile(
      path.join(platformDir, `${entryPoint}.js`),
      buildSandboxShimModule(entryPoint, GENERATED_MODULE_MARKER),
      "utf8",
    );
  }

  for (const root of roots) {
    const rootDir = path.join(releaseDir, root);
    let slot = root;
    const sandboxDir = path.join(rootDir, "sandbox");
    const sandboxKind = await pathKind(sandboxDir);
    if (sandboxKind === "directory") {
      // eve resolves `sandbox/` before `sandbox.<ext>`, and the directory
      // carries the workspace seeds, so the module lives inside it and a flat
      // module beside it is shadowed.
      slot = path.posix.join(root, "sandbox");
      replaced.push(...(await removeAuthoredSandboxModules(rootDir, root)));
    } else if (sandboxKind !== null) {
      await rm(sandboxDir, { force: true, recursive: true });
      replaced.push(path.posix.join(root, "sandbox"));
    }

    const slotDir = path.join(releaseDir, slot);
    const authored = await keepEffectiveAuthoredModule(slotDir, slot);
    replaced.push(...authored.replaced);
    const toPlatform = path.posix.relative(slot, SANDBOX_PLATFORM_DIR);
    if (authored.modulePath) {
      const source = await readFile(authored.modulePath, "utf8");
      const result = rewriteEveSandboxImports(
        source,
        (entryPoint) => `${toPlatform}/${entryPoint}.js`,
      );
      if (result.source !== source) await writeFile(authored.modulePath, result.source, "utf8");
      rewritten.push(path.posix.join(slot, path.basename(authored.modulePath)));
      continue;
    }
    await writeFile(
      path.join(slotDir, "sandbox.js"),
      buildGeneratedProviderSandboxModule(`${toPlatform}/platform.js`, GENERATED_MODULE_MARKER),
      "utf8",
    );
    generated.push(path.posix.join(slot, "sandbox.js"));
  }

  return { generated, rewritten, replaced };
}

/**
 * Finds the authored module eve would load from one slot and removes the
 * rest: lower-priority duplicates it would shadow, anything that is not a
 * regular file, and this function's own earlier output.
 */
async function keepEffectiveAuthoredModule(
  slotDir: string,
  slot: string,
): Promise<{ modulePath?: string; replaced: string[] }> {
  const replaced: string[] = [];
  let modulePath: string | undefined;
  for (const extension of AUTHORED_MODULE_EXTENSIONS) {
    const candidate = path.join(slotDir, `sandbox${extension}`);
    const kind = await pathKind(candidate);
    if (kind === null) continue;
    const logicalPath = path.posix.join(slot, `sandbox${extension}`);
    if (kind !== "file") {
      await rm(candidate, { force: true, recursive: true });
      replaced.push(logicalPath);
      continue;
    }
    const contents = await readFile(candidate, "utf8").catch(() => "");
    const isOwnOutput = extension === ".js" && contents.startsWith(GENERATED_MODULE_MARKER);
    if (isOwnOutput || modulePath !== undefined) {
      await rm(candidate, { force: true });
      if (!isOwnOutput) replaced.push(logicalPath);
      continue;
    }
    modulePath = candidate;
  }
  return { ...(modulePath ? { modulePath } : {}), replaced };
}
