import { access, cp, mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/** Where the built backend is vendored inside the release directory. */
export const VENDORED_BACKEND_DIR = ".eveland/sandbox-bwrap";

/** Extensions eve accepts for an authored module, highest resolution priority first. */
const AUTHORED_MODULE_EXTENSIONS = [".cts", ".mts", ".cjs", ".mjs", ".ts", ".js"] as const;

/**
 * First line of every module this file generates. `.js` is both an authored
 * module extension eve resolves and the extension we always write, so a
 * re-run must tell its own previous output apart from a project's authored
 * `sandbox.js` by content, not by path. Exported so `buildGeneratedSandboxModule`
 * and the removal loop can never drift apart.
 */
export const GENERATED_MODULE_MARKER = "// Generated by eveland at build time.";

/** Same-directory companion name used to preserve an authored definition's relative imports. */
const WRAPPED_MODULE_BASENAME = ".sandbox.eveland-authored";

export type SandboxInjectionInput = {
  releaseDir: string;
  /** Directory holding the built @evelandhq/sandbox-bwrap (its dist/). */
  backendDistDir: string;
};

export type SandboxInjectionResult = {
  /** Paths (relative to releaseDir) of generated sandbox modules. */
  generated: string[];
  /** Authored definitions whose lifecycle fields are retained by the generated wrapper. */
  wrapped: string[];
  /** Paths (relative to releaseDir) of authored sandbox modules that were replaced. */
  replaced: string[];
};

export function resolveSandboxRunTimeoutMs(env: NodeJS.ProcessEnv): string {
  const value = Number(env.EVELAND_SANDBOX_RUN_TIMEOUT_MS ?? 600_000);
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error("EVELAND_SANDBOX_RUN_TIMEOUT_MS must be a positive safe integer.");
  }
  return String(value);
}

export function buildGeneratedSandboxModule(
  relativeImportPath: string,
  authoredImportPath?: string,
): string {
  const authoredImport = authoredImportPath
    ? `import authoredSandbox from ${JSON.stringify(authoredImportPath)};\n`
    : "";
  const authoredFields = authoredImportPath ? "  ...authoredSandbox,\n" : "";
  return `${GENERATED_MODULE_MARKER} Do not edit.
// The deploy host decides the sandbox backend; agent projects never declare one.
import { defineSandbox, defaultBackend } from "eve/sandbox";
import { bwrap, isBwrapAvailable } from "${relativeImportPath}";
${authoredImport}
const cacheDir = process.env.EVELAND_SANDBOX_CACHE_DIR;
const templateRevision = process.env.EVELAND_SANDBOX_TEMPLATE_REVISION;
const runTimeoutMs = Number(process.env.EVELAND_SANDBOX_RUN_TIMEOUT_MS ?? "600000");
const bwrapOptions = {
  ...(cacheDir ? { cacheDir } : {}),
  ...(templateRevision ? { templateRevision } : {}),
  runTimeoutMs,
};

export default defineSandbox({
${authoredFields}  // Eveland owns only the backend. Authored lifecycle and metadata stay active.
  backend: () => (isBwrapAvailable() ? bwrap(bwrapOptions) : defaultBackend()),
});
`;
}

async function listDirectories(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
}

async function pathKind(target: string): Promise<"file" | "directory" | "other" | null> {
  const entries = await readdir(path.dirname(target), { withFileTypes: true }).catch(() => []);
  const match = entries.find((entry) => entry.name === path.basename(target));
  if (!match) return null;
  if (match.isDirectory()) return "directory";
  if (match.isFile()) return "file";
  return "other";
}

async function removeAuthoredSandboxModules(
  moduleDir: string,
  relativeDir: string,
): Promise<string[]> {
  const removed: string[] = [];
  for (const extension of AUTHORED_MODULE_EXTENSIONS) {
    const authored = path.join(moduleDir, `sandbox${extension}`);
    const kind = await pathKind(authored);
    if (kind === "other") {
      await rm(authored, { force: true, recursive: true });
      removed.push(path.posix.join(relativeDir, `sandbox${extension}`));
      continue;
    }
    if (kind !== "file") continue;

    const contents = await readFile(authored, "utf8").catch(() => "");
    await rm(authored, { force: true });
    // `.js` is both an authored extension and what eveland generates. A re-run
    // must not report its own previous output as authored behavior it replaced.
    if (extension !== ".js" || !contents.startsWith(GENERATED_MODULE_MARKER)) {
      removed.push(path.posix.join(relativeDir, `sandbox${extension}`));
    }
  }
  return removed;
}

type WrappedAuthoredSandbox = {
  importPath?: string;
  replaced: string[];
  wrapped: string[];
};

/**
 * Moves the effective authored definition to a non-discoverable companion in
 * the same directory. Keeping it beside the original slot preserves all of
 * its relative imports; the generated sandbox.js imports and spreads it before
 * overriding only `backend`.
 */
async function wrapAuthoredSandboxModule(
  moduleDir: string,
  relativeDir: string,
): Promise<WrappedAuthoredSandbox> {
  type Candidate = {
    extension: (typeof AUTHORED_MODULE_EXTENSIONS)[number];
    path: string;
  };
  const authored: Candidate[] = [];
  const companions: Candidate[] = [];
  const replaced: string[] = [];
  let generatedModuleSeen = false;

  for (const extension of AUTHORED_MODULE_EXTENSIONS) {
    const modulePath = path.join(moduleDir, `sandbox${extension}`);
    const moduleKind = await pathKind(modulePath);
    if (moduleKind === "other") {
      await rm(modulePath, { force: true, recursive: true });
      replaced.push(path.posix.join(relativeDir, `sandbox${extension}`));
    } else if (moduleKind === "file") {
      const contents = await readFile(modulePath, "utf8").catch(() => "");
      if (extension === ".js" && contents.startsWith(GENERATED_MODULE_MARKER)) {
        generatedModuleSeen = true;
        await rm(modulePath, { force: true });
      } else {
        authored.push({ extension, path: modulePath });
      }
    }

    const companionPath = path.join(moduleDir, `${WRAPPED_MODULE_BASENAME}${extension}`);
    const companionKind = await pathKind(companionPath);
    if (companionKind === "file") {
      companions.push({ extension, path: companionPath });
    } else if (companionKind !== null) {
      throw new Error(
        `Cannot preserve authored sandbox in ${relativeDir}: reserved companion path collision at ${companionPath}.`,
      );
    }
  }

  if (companions.length > 1 || (companions.length === 1 && !generatedModuleSeen)) {
    throw new Error(
      `Cannot preserve authored sandbox in ${relativeDir}: reserved companion path collision for ${WRAPPED_MODULE_BASENAME}.`,
    );
  }
  if (companions.length === 1 && authored.length > 0) {
    throw new Error(
      `Cannot preserve authored sandbox in ${relativeDir}: both an authored module and an existing Eveland companion are present.`,
    );
  }

  let wrappedModule = companions[0];
  let wrappedLogicalPath: string | undefined;
  if (wrappedModule) {
    wrappedLogicalPath = path.posix.join(relativeDir, `sandbox${wrappedModule.extension}`);
  } else if (authored.length > 0) {
    const [effective, ...shadowed] = authored;
    wrappedModule = {
      extension: effective!.extension,
      path: path.join(moduleDir, `${WRAPPED_MODULE_BASENAME}${effective!.extension}`),
    };
    await rename(effective!.path, wrappedModule.path);
    wrappedLogicalPath = path.posix.join(relativeDir, `sandbox${effective!.extension}`);
    for (const extra of shadowed) {
      await rm(extra.path, { force: true });
      replaced.push(path.posix.join(relativeDir, `sandbox${extra.extension}`));
    }
  }

  return {
    ...(wrappedModule ? { importPath: `./${path.basename(wrappedModule.path)}` } : {}),
    replaced,
    wrapped: wrappedLogicalPath ? [wrappedLogicalPath] : [],
  };
}

/**
 * Every directory that owns a sandbox: the agent root plus every subagent,
 * however deeply nested.
 *
 * eve resolves subagents from `agent/subagents/<name>/` (confirmed against
 * eve 0.29.5's `discoverSubagents`, which defaults `subagentsDirectoryPath`
 * to `join(agentRoot, "subagents")`). `discoverLocalSubagentPackage` then
 * calls `discoverSandboxSource({ rootPath: subagentRoot })` *and*
 * `discoverSubagents({ agentRoot: subagentRoot })` for each directory-form
 * subagent it finds, so subagents can themselves declare further subagents
 * at `<subagentRoot>/subagents/<name>/`, arbitrarily deep — each level owns
 * its own sandbox slot. Only directory-form subagents own a sandbox (a
 * file-form subagent like `subagents/foo.ts` does not), so we only recurse
 * into directory children.
 */
async function collectSandboxRoots(
  releaseDir: string,
  root: string,
  roots: string[],
): Promise<void> {
  roots.push(root);
  const subagentsDir = path.join(releaseDir, root, "subagents");
  for (const name of await listDirectories(subagentsDir)) {
    await collectSandboxRoots(releaseDir, path.posix.join(root, "subagents", name), roots);
  }
}

export async function resolveSandboxRoots(releaseDir: string): Promise<string[]> {
  const agentDir = path.join(releaseDir, "agent");
  if ((await pathKind(agentDir)) !== "directory") return [];
  const roots: string[] = [];
  await collectSandboxRoots(releaseDir, "agent", roots);
  return roots;
}

export async function injectSandboxModules(
  input: SandboxInjectionInput,
): Promise<SandboxInjectionResult> {
  const roots = await resolveSandboxRoots(input.releaseDir);
  const generated: string[] = [];
  const wrapped: string[] = [];
  const replaced: string[] = [];

  // Vendoring is a host-capability concern -- it must happen for every release
  // regardless of project layout, so `verifySandbox` (which imports the
  // vendored backend as a sibling module) always has something to import, even
  // when this project has no agent/ directory and therefore generates no
  // sandbox module below.
  const backendEntryPoint = path.join(input.backendDistDir, "index.js");
  const backendIsBuilt = await access(backendEntryPoint).then(
    () => true,
    () => false,
  );
  if (!backendIsBuilt) {
    throw new Error(
      `@evelandhq/sandbox-bwrap backend is unusable: ${input.backendDistDir} has no index.js. ` +
        "The package ships prebuilt, so this means an incomplete install. Run `pnpm install`, then retry.",
    );
  }

  const vendorDir = path.join(input.releaseDir, VENDORED_BACKEND_DIR);
  await rm(vendorDir, { force: true, recursive: true });
  await mkdir(path.dirname(vendorDir), { recursive: true });
  await cp(input.backendDistDir, vendorDir, { recursive: true });

  for (const root of roots) {
    const rootDir = path.join(input.releaseDir, root);
    let generatedRoot = root;
    let authoredImportPath: string | undefined;

    // eve resolves `sandbox/` before `sandbox.<ext>`. A real directory must
    // survive so its `workspace/**` seeds are compiled; generate the platform
    // backend inside that directory and wrap its authored definition.
    // A file or symlink named `sandbox` cannot safely carry workspace seeds,
    // so remove it and fall back to the flat generated-module shape.
    const sandboxDir = path.join(rootDir, "sandbox");
    const sandboxKind = await pathKind(sandboxDir);
    if (sandboxKind === "directory") {
      generatedRoot = path.posix.join(root, "sandbox");
      const authored = await wrapAuthoredSandboxModule(sandboxDir, generatedRoot);
      authoredImportPath = authored.importPath;
      wrapped.push(...authored.wrapped);
      replaced.push(...authored.replaced);
      // Eve's folder layout wins discovery, so a flat definition is shadowed
      // and cannot contribute lifecycle behavior.
      replaced.push(...(await removeAuthoredSandboxModules(rootDir, root)));
    } else if (sandboxKind !== null) {
      await rm(sandboxDir, { force: true, recursive: true });
      replaced.push(path.posix.join(root, "sandbox"));
      replaced.push(...(await removeAuthoredSandboxModules(rootDir, root)));
    } else {
      const authored = await wrapAuthoredSandboxModule(rootDir, root);
      authoredImportPath = authored.importPath;
      wrapped.push(...authored.wrapped);
      replaced.push(...authored.replaced);
    }

    const importPath = path.posix.join(
      path.posix.relative(generatedRoot, ""),
      VENDORED_BACKEND_DIR,
      "index.js",
    );
    await writeFile(
      path.join(input.releaseDir, generatedRoot, "sandbox.js"),
      buildGeneratedSandboxModule(importPath, authoredImportPath),
      "utf8",
    );
    generated.push(path.posix.join(generatedRoot, "sandbox.js"));
  }

  return { generated, replaced, wrapped };
}
