import { access, readdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";

export const PLATFORM_WORKFLOW_WORLD = {
  packageName: "@workflow/world-postgres",
  packageVersion: "5.0.0-beta.25",
} as const;

export type WorkflowWorldBuildConfig = typeof PLATFORM_WORKFLOW_WORLD;

export type WorkflowWorldInjectionResult = {
  agentConfigPath: string;
  authoredConfigPath?: string;
};

const agentConfigPattern = /^agent\.(?:cts|mts|cjs|mjs|ts|js)$/;
const defaultEveAgentModel = "anthropic/claude-sonnet-5";

export function buildWorkflowWorldInstallCommand(config: WorkflowWorldBuildConfig): string {
  return `npm install --no-save --package-lock=false --ignore-scripts ${config.packageName}@${config.packageVersion}`;
}

export async function injectWorkflowWorld(input: {
  releaseDir: string;
  config: WorkflowWorldBuildConfig;
}): Promise<WorkflowWorldInjectionResult> {
  const releaseDir = path.resolve(input.releaseDir);
  const nestedAgentRoot = path.join(releaseDir, "agent");
  const agentRoot = (await isDirectory(nestedAgentRoot)) ? nestedAgentRoot : releaseDir;
  const entries = await readdir(agentRoot).catch(() => []);
  const authoredConfigs = entries.filter((entry) => agentConfigPattern.test(entry));

  if (authoredConfigs.length > 1) {
    throw new Error(
      `Cannot inject the platform workflow world: multiple root agent config modules were found (${authoredConfigs.join(", ")}).`,
    );
  }

  const generatedConfigPath = path.join(agentRoot, "agent.ts");
  let authoredConfigPath: string | undefined;
  let source: string;
  const [authoredConfig] = authoredConfigs;

  if (authoredConfig) {
    const extension = path.extname(authoredConfig);
    const reservedName = `eveland-authored-agent${extension}`;
    const reservedPath = path.join(agentRoot, reservedName);
    if (await exists(reservedPath)) {
      throw new Error(
        `Reserved workflow-world config already exists at ${path.relative(releaseDir, reservedPath)}. Rename the authored file; Eveland will not overwrite it.`,
      );
    }
    await rename(path.join(agentRoot, authoredConfig), reservedPath);
    authoredConfigPath = path.relative(releaseDir, reservedPath);
    source = createWrappedAgentConfigSource(reservedName, input.config.packageName);
  } else {
    source = createDefaultAgentConfigSource(input.config.packageName);
  }

  await writeFile(generatedConfigPath, source, "utf8");
  return {
    agentConfigPath: path.relative(releaseDir, generatedConfigPath),
    ...(authoredConfigPath ? { authoredConfigPath } : {}),
  };
}

function createWrappedAgentConfigSource(authoredFileName: string, world: string): string {
  return `// Generated by Eveland in the prepared Release; imported source is unchanged.
import authoredAgentConfig from ${JSON.stringify(`./${authoredFileName}`)};

const authoredAgent = authoredAgentConfig as Record<string, unknown> & {
  experimental?: Record<string, unknown> & {
    workflow?: Record<string, unknown>;
  };
};

export default {
  ...authoredAgent,
  experimental: {
    ...authoredAgent.experimental,
    workflow: {
      ...authoredAgent.experimental?.workflow,
      world: ${JSON.stringify(world)},
    },
  },
};
`;
}

function createDefaultAgentConfigSource(world: string): string {
  return `// Generated by Eveland in the prepared Release; imported source is unchanged.
export default {
  model: ${JSON.stringify(defaultEveAgentModel)},
  experimental: {
    workflow: {
      world: ${JSON.stringify(world)},
    },
  },
};
`;
}

async function isDirectory(target: string): Promise<boolean> {
  return readdir(target).then(() => true, () => false);
}

async function exists(target: string): Promise<boolean> {
  return access(target).then(() => true, () => false);
}
